/** @module components/graphics/2D/Align */
import { Component, Css, Templates } from '../../../core/index.ts';const html=Templates.Template.Html;
export namespace Align
{
 export type AlignAction='left'|'hcenter'|'right'|'top'|'vcenter'|'bottom'|'distribute-h'|'distribute-v';
 export interface AlignOptions{theme?:'dark'|'light';relativeTo?:'selection'|'key-object'|'artboard';}
 export const Styles=new Css.Stylesheet([
  new Css.Rule('.Align',{Background:'#202428',Border:'1px solid #121517',BorderRadius:'8px',BoxSizing:'border-box',Color:'#e5e8ea',Display:'block',FontFamily:'var(--arianna-font,system-ui,sans-serif)',Overflow:'hidden',Width:'290px'}),new Css.Rule('.Align-Header',{Background:'linear-gradient(180deg,#363b40,#25292d)',BorderBottom:'1px solid #111417',FontSize:'10px',FontWeight:'760',Padding:'8px 10px'}),new Css.Rule('.Align-Body',{Display:'grid',Gap:'9px',Padding:'10px'}),new Css.Rule('.Align-Group',{Display:'grid',Gap:'4px',GridTemplateColumns:'repeat(3,1fr)'}),new Css.Rule('.Align-Button',{AlignItems:'center',Appearance:'none',Background:'linear-gradient(180deg,#444a50,#30353a)',Border:'1px solid #15181a',BorderRadius:'3px',Color:'#dce0e3',Cursor:'pointer',Display:'flex',Font:'700 12px/1 system-ui',Height:'31px',JustifyContent:'center'}),new Css.Rule('.Align-Button:hover',{BorderColor:'#e40c88',Color:'#ff67b7'}),new Css.Rule('.Align-Select',{Appearance:'none',Background:'#181c20',Border:'1px solid #3b4147',BorderRadius:'4px',Color:'#e5e8ea',Font:'9px var(--arianna-font,system-ui,sans-serif)',Padding:'7px'}),new Css.Rule('.Align[theme="light"]',{Background:'#eef0f2',BorderColor:'#b9bec3',Color:'#25292d'}),new Css.Rule('.Align[theme="light"] .Align-Header',{Background:'linear-gradient(180deg,#f9fafb,#dfe3e6)',BorderBottomColor:'#b9bec3'}),new Css.Rule('.Align[theme="light"] .Align-Button',{Background:'linear-gradient(180deg,#fff,#e1e4e7)',BorderColor:'#b9bec3',Color:'#383e43'}),new Css.Rule('.Align[theme="light"] .Align-Select',{Background:'#fff',BorderColor:'#c1c6cb',Color:'#30363b'})
 ]);
 @Component('arianna-align',Styles,{Shadow:false,Attributes:['theme','relative-to']}) export class Align extends HTMLDivElement
 {public static readonly Styles=Styles;public template=html``;constructor(o:AlignOptions={}){super();if(o.theme)this.setAttribute('theme',o.theme);if(o.relativeTo)this.setAttribute('relative-to',o.relativeTo);}public onCreated(){requestAnimationFrame(()=>{if(this.isConnected)this.onConnected();});}public onConnected(){this.classList.add('Align');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');this.Render();}private Emit(action:AlignAction){this.dispatchEvent(new CustomEvent('arianna:align',{bubbles:true,composed:true,detail:{action,relativeTo:this.getAttribute('relative-to')||'selection'}}));}private Render(){const r=document.createElement('section'),h=document.createElement('header');h.className='Align-Header';h.textContent='Align';const b=document.createElement('div');b.className='Align-Body';const a=document.createElement('div');a.className='Align-Group';for(const [id,ico] of [['left','|▮'],['hcenter','▮|▮'],['right','▮|'],['top','¯▮'],['vcenter','▮—'],['bottom','_▮']] as [AlignAction,string][]){const x=document.createElement('button');x.className='Align-Button';x.textContent=ico;x.title=id;x.onclick=()=>this.Emit(id);a.append(x);}const d=document.createElement('div');d.className='Align-Group';for(const [id,ico] of [['distribute-h','▮ ↔ ▮'],['distribute-v','▮ ↕ ▮']] as [AlignAction,string][]){const x=document.createElement('button');x.className='Align-Button';x.style.gridColumn='span 1';x.textContent=ico;x.onclick=()=>this.Emit(id);d.append(x);}const s=document.createElement('select');s.className='Align-Select';s.innerHTML='<option value="selection">Align to Selection</option><option value="key-object">Align to Key Object</option><option value="artboard">Align to Artboard</option>';s.value=this.getAttribute('relative-to')||'selection';s.onchange=()=>this.setAttribute('relative-to',s.value);b.append(a,d,s);r.append(h,b);this.replaceChildren(r);}}
}
export type AlignOptions=Align.AlignOptions;export type AlignAction=Align.AlignAction;export default Align.Align;
