/** @module components/graphics/2D/ToolsPalette */
import { Component, Css, Templates } from '../../../core/index.ts';const html=Templates.Template.Html;
export namespace ToolsPalette
{
 export namespace Interfaces{export interface PaletteTool{id:string;label:string;icon?:string;shortcut?:string;}export interface ToolsPaletteOptions{tools?:PaletteTool[];selected?:string;columns?:1|2;theme?:'dark'|'light';}}
 const T:Interfaces.PaletteTool[]=[{id:'select',label:'Selection',icon:'↖'},{id:'direct',label:'Direct Selection',icon:'⌁'},{id:'wand',label:'Magic Wand',icon:'✦'},{id:'lasso',label:'Lasso',icon:'◌'},{id:'pen',label:'Pen',icon:'✒'},{id:'curve',label:'Curvature',icon:'⌒'},{id:'type',label:'Text',icon:'T'},{id:'line',label:'Line',icon:'╱'},{id:'rect',label:'Rectangle',icon:'□'},{id:'brush',label:'Paintbrush',icon:'╲'},{id:'pencil',label:'Pencil',icon:'✎'},{id:'eraser',label:'Eraser',icon:'▱'},{id:'rotate',label:'Rotate',icon:'↻'},{id:'scale',label:'Scale',icon:'↗'},{id:'width',label:'Width',icon:'↔'},{id:'gradient',label:'Gradient',icon:'◩'},{id:'eyedropper',label:'Eyedropper',icon:'⌁'},{id:'hand',label:'Hand',icon:'✋'},{id:'zoom',label:'Zoom',icon:'⌕'}];
 export const Styles=new Css.Stylesheet([
  new Css.Rule('.ToolsPalette',{Background:'#25292d',Border:'1px solid #121517',BorderRadius:'7px',BoxSizing:'border-box',Color:'#e5e8ea',Display:'block',FontFamily:'var(--arianna-font,system-ui,sans-serif)',Overflow:'hidden',Width:'76px'}),new Css.Rule('.ToolsPalette-Grip',{Background:'linear-gradient(180deg,#363b40,#25292d)',BorderBottom:'1px solid #111417',Color:'#8f979f',FontSize:'9px',Padding:'5px',TextAlign:'center'}),new Css.Rule('.ToolsPalette-Grid',{Display:'grid',Gap:'2px',GridTemplateColumns:'repeat(var(--cols,2),1fr)',Padding:'4px'}),new Css.Rule('.ToolsPalette-Tool',{AlignItems:'center',Appearance:'none',Background:'transparent',Border:'1px solid transparent',BorderRadius:'3px',Color:'#c9cfd4',Cursor:'pointer',Display:'flex',Font:'600 14px/1 var(--arianna-font,system-ui,sans-serif)',Height:'31px',JustifyContent:'center',Padding:'0'}),new Css.Rule('.ToolsPalette-Tool:hover',{Background:'#33383d',BorderColor:'#42484e'}),new Css.Rule('.ToolsPalette-Tool[data-selected="true"]',{Background:'linear-gradient(180deg,#e40c88,#bd0b73)',BorderColor:'#9d075f',Color:'#fff'}),new Css.Rule('.ToolsPalette-Colors',{Display:'grid',GridTemplateColumns:'1fr 1fr',Padding:'7px 9px 9px',Position:'relative'}),new Css.Rule('.ToolsPalette-Fill,.ToolsPalette-Stroke',{Border:'2px solid #cfd4d8',Height:'24px',Width:'24px'}),new Css.Rule('.ToolsPalette-Fill',{Background:'#e40c88',ZIndex:'2'}),new Css.Rule('.ToolsPalette-Stroke',{Background:'#fff',MarginLeft:'-8px',MarginTop:'8px',ZIndex:'1'}),new Css.Rule('.ToolsPalette[theme="light"]',{Background:'#eef0f2',BorderColor:'#b9bec3',Color:'#25292d'}),new Css.Rule('.ToolsPalette[theme="light"] .ToolsPalette-Grip',{Background:'linear-gradient(180deg,#f9fafb,#dfe3e6)',BorderBottomColor:'#b9bec3'}),new Css.Rule('.ToolsPalette[theme="light"] .ToolsPalette-Tool',{Color:'#4c5359'}),new Css.Rule('.ToolsPalette[theme="light"] .ToolsPalette-Tool:hover',{Background:'#dfe3e6',BorderColor:'#c3c8cc'})
 ]);
 @Component('arianna-tools-palette',Styles,{Shadow:false,Attributes:['theme','selected','columns'],Properties:['tools']}) export class ToolsPalette extends HTMLDivElement
 {public static readonly Styles=Styles;public template=html``;private _tools=[...T];private _selected='select';constructor(o:Interfaces.ToolsPaletteOptions={}){super();if(o.theme)this.setAttribute('theme',o.theme);if(o.tools)this._tools=o.tools;if(o.selected)this._selected=o.selected;if(o.columns)this.setAttribute('columns',String(o.columns));}public onCreated(){requestAnimationFrame(()=>{if(this.isConnected)this.onConnected();});}public onConnected(){this.classList.add('ToolsPalette');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');this._selected=this.getAttribute('selected')||this._selected;this.Render();}public get tools(){return this._tools;}public set tools(v:Interfaces.PaletteTool[]){this._tools=v;this.Render();}public setTool(id:string):this{if(this._tools.some(t=>t.id===id)){this._selected=id;this.setAttribute('selected',id);this.Render();}return this;}public getTool():string|null{return this._selected||null;}public setTools(tools:Interfaces.PaletteTool[]):this{this.tools=tools;return this;}public onBeforeMount(){}public onMount(){}public onBeforeUpdate(){}public onUpdate(){}public onBeforeUnmount(){}public onUnmount(){}private Render(){this.style.setProperty('--cols',this.getAttribute('columns')||'2');const r=document.createElement('section'),g=document.createElement('div');g.className='ToolsPalette-Grip';g.textContent='•••';const grid=document.createElement('div');grid.className='ToolsPalette-Grid';for(const t of this._tools){const b=document.createElement('button');b.className='ToolsPalette-Tool';b.dataset.selected=String(t.id===this._selected);b.title=t.label+(t.shortcut?` (${t.shortcut})`:'');b.textContent=t.icon||t.label[0];b.onclick=()=>{this._selected=t.id;this.setAttribute('selected',t.id);this.dispatchEvent(new CustomEvent('arianna:tool',{bubbles:true,composed:true,detail:{tool:t}}));this.Render();};grid.append(b);}const colors=document.createElement('div');colors.className='ToolsPalette-Colors';colors.innerHTML='<div class="ToolsPalette-Fill"></div><div class="ToolsPalette-Stroke"></div>';r.append(g,grid,colors);this.replaceChildren(r);}}
}
export type PaletteTool=ToolsPalette.Interfaces.PaletteTool;export type ToolsPaletteOptions=ToolsPalette.Interfaces.ToolsPaletteOptions;export default ToolsPalette.ToolsPalette;
