/** @module components/payments
 * @description Canonical payment barrel. Every provider except PaymentGateway and
 * CreditCard is a single PaymentButton with API + Mode configuration.
 */
import { PaymentButton as PaymentButtonModule } from './PaymentButton.ts';
import { ApplePay as ApplePayModule } from './ApplePay.ts';
import { GooglePay as GooglePayModule } from './GooglePay.ts';
import { CreditCard as CreditCardModule } from './CreditCard.ts';
import { PayPal as PayPalModule } from './PayPal.ts';
import { Stripe as StripeModule } from './Stripe.ts';
import { Satispay as SatispayModule } from './Satispay.ts';
import { Nexi as NexiModule } from './Nexi.ts';
import { AliPay as AliPayModule } from './AliPay.ts';
import { WeChatPay as WeChatPayModule } from './WeChatPay.ts';
import { AmazonPay as AmazonPayModule } from './AmazonPay.ts';
import { Klarna as KlarnaModule } from './Klarna.ts';
import { Sofort as SofortModule } from './Sofort.ts';
import { Adyen as AdyenModule } from './Adyen.ts';
import { Worldline as WorldlineModule } from './Worldline.ts';
import { CheckoutCom as CheckoutComModule } from './CheckoutCom.ts';
import { SumUp as SumUpModule } from './SumUp.ts';
import { Mollie as MollieModule } from './Mollie.ts';
import { TWINT as TWINTModule } from './TWINT.ts';
import { Ideal as IdealModule } from './Ideal.ts';
import { Bancontact as BancontactModule } from './Bancontact.ts';
import { BLIK as BLIKModule } from './BLIK.ts';
import { Trustly as TrustlyModule } from './Trustly.ts';
import { Wero as WeroModule } from './Wero.ts';
import { SEPA as SEPAModule } from './SEPA.ts';
import { Pix as PixModule } from './Pix.ts';
import { UPI as UPIModule } from './UPI.ts';
import { MercadoPago as MercadoPagoModule } from './MercadoPago.ts';
import { MPesa as MPesaModule } from './MPesa.ts';
import { CashApp as CashAppModule } from './CashApp.ts';
import { HostedPayment as HostedPaymentModule } from './HostedPayment.ts';
import { PaymentGateway as PaymentGatewayModule } from './PaymentGateway.ts';

export { PaymentProviders } from './Providers.ts';
export type { PaymentProviderId, PaymentProviderKind, PaymentProviderConfig, PaymentApiCapability } from './Providers.ts';

export const PaymentButton=PaymentButtonModule.PaymentButton;
export const ApplePay=ApplePayModule.ApplePay;
export const GooglePay=GooglePayModule.GooglePay;
export const CreditCard=CreditCardModule.CreditCard;
export const PayPal=PayPalModule.PayPal;
export const Stripe=StripeModule.Stripe;
export const Satispay=SatispayModule.Satispay;
export const Nexi=NexiModule.Nexi;
export const AliPay=AliPayModule.AliPay;
export const WeChatPay=WeChatPayModule.WeChatPay;
export const AmazonPay=AmazonPayModule.AmazonPay;
export const Klarna=KlarnaModule.Klarna;
export const Sofort=SofortModule.Sofort;
export const Adyen=AdyenModule.Adyen;
export const Worldline=WorldlineModule.Worldline;
export const CheckoutCom=CheckoutComModule.CheckoutCom;
export const SumUp=SumUpModule.SumUp;
export const Mollie=MollieModule.Mollie;
export const TWINT=TWINTModule.TWINT;
export const Ideal=IdealModule.Ideal;
export const Bancontact=BancontactModule.Bancontact;
export const BLIK=BLIKModule.BLIK;
export const Trustly=TrustlyModule.Trustly;
export const Wero=WeroModule.Wero;
export const SEPA=SEPAModule.SEPA;
export const Pix=PixModule.Pix;
export const UPI=UPIModule.UPI;
export const MercadoPago=MercadoPagoModule.MercadoPago;
export const MPesa=MPesaModule.MPesa;
export const CashApp=CashAppModule.CashApp;
export const HostedPayment=HostedPaymentModule.HostedPayment;
export const PaymentGateway=PaymentGatewayModule.PaymentGateway;

export type PaymentMode=PaymentButtonModule.Types.PaymentMode;
export type PaymentAPI=PaymentButtonModule.Interfaces.PaymentAPI;
export type PaymentButtonOptions=PaymentButtonModule.Interfaces.PaymentButtonOptions;
export type PaymentRequest=PaymentButtonModule.Interfaces.PaymentRequest;
export type PaymentResult=PaymentButtonModule.Interfaces.PaymentResult;
export type ApplePayOptions=ApplePayModule.Interfaces.ApplePayOptions;
export type GooglePayOptions=GooglePayModule.Interfaces.GooglePayOptions;
export type CardBrand=CreditCardModule.Types.CardBrand;
export type CardData=CreditCardModule.Interfaces.CardData;
export type CreditCardOptions=CreditCardModule.Interfaces.CreditCardOptions;
export type PayPalOptions=PayPalModule.Interfaces.PayPalOptions;
export type StripeOptions=StripeModule.Interfaces.StripeOptions;
export type SatispayOptions=SatispayModule.Interfaces.SatispayOptions;
export type NexiOptions=NexiModule.Interfaces.NexiOptions;
export type AliPayMode=AliPayModule.Types.AliPayMode;
export type AliPayOptions=AliPayModule.Interfaces.AliPayOptions;
export type HostedPaymentOptions=HostedPaymentModule.HostedPaymentOptions;
export type PaymentMethodId=PaymentGatewayModule.Types.PaymentMethodId;
export type PaymentGatewayMethodConfig=PaymentGatewayModule.Interfaces.PaymentGatewayMethodConfig;
export type PaymentGatewayOptions=PaymentGatewayModule.Interfaces.PaymentGatewayOptions;
