/** @module components/graphics/colors/ColorPickerSquare */
import { Component, Css, Templates } from '../../../core/index.ts';
import { hslToRgb, rgbToHex, rgbToHsl, parseHexRgba } from './GraphicsColorPicker.ts';
const html=Templates.Template.Html;
export namespace ColorPickerSquare
{
    export namespace Interfaces{export interface ColorPickerSquareOptions{value?:string;theme?:'dark'|'light';alpha?:boolean;}export interface HSVState{h:number;s:number;v:number;a:number;}}
    export const Styles=new Css.Stylesheet([
        new Css.Rule('.ColorPickerSquare',{Background:'#202428',Border:'1px solid #121517',BorderRadius:'8px',BoxSizing:'border-box',Color:'#e5e8ea',Display:'block',FontFamily:'var(--arianna-font,system-ui,sans-serif)',Overflow:'hidden',Width:'285px'}),
        new Css.Rule('.ColorPickerSquare-Header',{Background:'linear-gradient(180deg,#363b40,#25292d)',BorderBottom:'1px solid #111417',FontSize:'10px',FontWeight:'760',Padding:'8px 10px'}),
        new Css.Rule('.ColorPickerSquare-Body',{Display:'grid',Gap:'9px',Padding:'10px'}),
        new Css.Rule('.ColorPickerSquare-Square',{Background:'linear-gradient(to top,#000,transparent),linear-gradient(to right,#fff,hsla(var(--hue,325),100%,50%,0)),hsl(var(--hue,325),100%,50%)',Border:'1px solid #111417',BorderRadius:'4px',Cursor:'crosshair',Height:'150px',Position:'relative'}),
        new Css.Rule('.ColorPickerSquare-Cursor',{Border:'2px solid #fff',BorderRadius:'50%',BoxShadow:'0 0 0 1px #000',Height:'12px',Position:'absolute',Transform:'translate(-50%,-50%)',Width:'12px'}),
        new Css.Rule('.ColorPickerSquare-Hue',{Appearance:'none',Background:'linear-gradient(90deg,#f00,#ff0,#0f0,#0ff,#00f,#f0f,#f00)',Border:'1px solid #111417',BorderRadius:'999px',Height:'10px',Margin:'0',Width:'100%'}),
        new Css.Rule('.ColorPickerSquare-Footer',{AlignItems:'center',Display:'grid',Gap:'8px',GridTemplateColumns:'36px 1fr'}),
        new Css.Rule('.ColorPickerSquare-Chip',{Background:'var(--color)',Border:'1px solid #101214',BorderRadius:'4px',Height:'30px'}),
        new Css.Rule('.ColorPickerSquare-Input',{Appearance:'none',Background:'#181c20',Border:'1px solid #3b4147',BorderRadius:'4px',Color:'#e5e8ea',Font:'10px ui-monospace,monospace',Outline:'none',Padding:'7px'}),
        new Css.Rule('.ColorPickerSquare[theme="light"]',{Background:'#eef0f2',BorderColor:'#b9bec3',Color:'#25292d'}),
        new Css.Rule('.ColorPickerSquare[theme="light"] .ColorPickerSquare-Header',{Background:'linear-gradient(180deg,#f9fafb,#dfe3e6)',BorderBottomColor:'#b9bec3'}),
        new Css.Rule('.ColorPickerSquare[theme="light"] .ColorPickerSquare-Input',{Background:'#fff',BorderColor:'#c1c6cb',Color:'#30363b'})
    ]);
    @Component('arianna-color-picker-square',Styles,{Shadow:false,Attributes:['value','theme']})
    export class ColorPickerSquare extends HTMLDivElement
    {public static readonly Styles=Styles;public template=html``;private _h=325;private _s=88;private _l=52;constructor(o:Interfaces.ColorPickerSquareOptions={}){super();if(o.theme)this.setAttribute('theme',o.theme);if(o.value)this.SetHex(o.value);}public onCreated(){requestAnimationFrame(()=>{if(this.isConnected)this.onConnected();});}public onConnected(){this.classList.add('ColorPickerSquare');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');const v=this.getAttribute('value');if(v)this.SetHex(v,false);this.Render();}private SetHex(v:string,emit=true){const p=parseHexRgba(v),h=rgbToHsl(p.r,p.g,p.b);this._h=h.h;this._s=h.s;this._l=h.l;if(emit)this.Emit();}private Hex(){const r=hslToRgb(this._h,this._s,this._l);return rgbToHex(r.r,r.g,r.b);}private Emit(){this.setAttribute('value',this.Hex());this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{value:this.Hex()}}));}public setColor(hex:string):this{this.SetHex(hex);return this;}public getColor(){const rgb=hslToRgb(this._h,this._s,this._l);return{hex:rgbToHex(rgb.r,rgb.g,rgb.b),rgb,hsl:{h:this._h,s:this._s,l:this._l}};}public onBeforeMount(){}public onMount(){}public onBeforeUpdate(){}public onUpdate(){}public onBeforeUnmount(){}public onUnmount(){}private Render(){this.style.setProperty('--hue',String(this._h));this.style.setProperty('--color',this.Hex());const root=document.createElement('section');const h=document.createElement('header');h.className='ColorPickerSquare-Header';h.textContent='Color Picker';const b=document.createElement('div');b.className='ColorPickerSquare-Body';const sq=document.createElement('div');sq.className='ColorPickerSquare-Square';const c=document.createElement('span');c.className='ColorPickerSquare-Cursor';c.style.left=`${this._s}%`;c.style.top=`${100-this._l}%`;sq.append(c);sq.onpointerdown=e=>{const r=sq.getBoundingClientRect();this._s=Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100));this._l=Math.max(0,Math.min(100,100-(e.clientY-r.top)/r.height*100));this.Emit();this.Render();};const hue=document.createElement('input');hue.type='range';hue.className='ColorPickerSquare-Hue';hue.min='0';hue.max='360';hue.value=String(this._h);hue.oninput=()=>{this._h=Number(hue.value);this.Emit();this.Render();};const f=document.createElement('div');f.className='ColorPickerSquare-Footer';const chip=document.createElement('div');chip.className='ColorPickerSquare-Chip';const input=document.createElement('input');input.className='ColorPickerSquare-Input';input.value=this.Hex();input.onchange=()=>{this.SetHex(input.value);this.Render();};f.append(chip,input);b.append(sq,hue,f);root.append(h,b);this.replaceChildren(root);}}
}
export type ColorPickerSquareOptions=ColorPickerSquare.Interfaces.ColorPickerSquareOptions;export default ColorPickerSquare.ColorPickerSquare;
