/** @module components/graphics/colors/ColorPickerWheel */
import { Component, Css, Templates } from '../../../core/index.ts';import { hslToRgb,rgbToHex,rgbToHsl,parseHexRgba } from './GraphicsColorPicker.ts';const html=Templates.Template.Html;
export namespace ColorPickerWheel
{
    export namespace Interfaces{export interface ColorPickerWheelOptions{value?:string;theme?:'dark'|'light';size?:number;}}
    export const Styles=new Css.Stylesheet([
        new Css.Rule('.ColorPickerWheel',{Background:'#202428',Border:'1px solid #121517',BorderRadius:'8px',BoxSizing:'border-box',Color:'#e5e8ea',Display:'block',FontFamily:'var(--arianna-font,system-ui,sans-serif)',Overflow:'hidden',Width:'300px'}),
        new Css.Rule('.ColorPickerWheel-Header',{Background:'linear-gradient(180deg,#363b40,#25292d)',BorderBottom:'1px solid #111417',FontSize:'10px',FontWeight:'760',Padding:'8px 10px'}),
        new Css.Rule('.ColorPickerWheel-Body',{AlignItems:'center',Display:'grid',Gap:'10px',JustifyItems:'center',Padding:'12px'}),
        new Css.Rule('.ColorPickerWheel-Wheel',{Background:'conic-gradient(#f00,#ff0,#0f0,#0ff,#00f,#f0f,#f00)',Border:'1px solid #0f1113',BorderRadius:'50%',BoxShadow:'inset 0 0 0 1px rgba(255,255,255,.05)',Cursor:'crosshair',Height:'210px',Position:'relative',Width:'210px'}),
        new Css.Rule('.ColorPickerWheel-Wheel::after',{Background:'radial-gradient(circle,#fff 0,rgba(255,255,255,.92) 12%,rgba(255,255,255,0) 64%),radial-gradient(circle at 50% 50%,transparent 0 56%,rgba(0,0,0,.88) 58% 66%,transparent 67%)',BorderRadius:'50%',Content:'""',Inset:'0',PointerEvents:'none',Position:'absolute'}),
        new Css.Rule('.ColorPickerWheel-Knob',{Background:'var(--color)',Border:'2px solid #fff',BorderRadius:'50%',BoxShadow:'0 0 0 1px #000,0 2px 6px rgba(0,0,0,.5)',Height:'15px',Left:'50%',Position:'absolute',Top:'7px',Transform:'translateX(-50%)',Width:'15px',ZIndex:'1'}),
        new Css.Rule('.ColorPickerWheel-Footer',{AlignItems:'center',Display:'grid',Gap:'8px',GridTemplateColumns:'34px 1fr',Width:'100%'}),new Css.Rule('.ColorPickerWheel-Chip',{Background:'var(--color)',Border:'1px solid #0f1113',BorderRadius:'4px',Height:'28px'}),new Css.Rule('.ColorPickerWheel-Input',{Background:'#181c20',Border:'1px solid #3b4147',BorderRadius:'4px',Color:'#e4e8eb',Font:'10px ui-monospace,monospace',Padding:'7px'}),
        new Css.Rule('.ColorPickerWheel[theme="light"]',{Background:'#eef0f2',BorderColor:'#b9bec3',Color:'#25292d'}),new Css.Rule('.ColorPickerWheel[theme="light"] .ColorPickerWheel-Header',{Background:'linear-gradient(180deg,#f9fafb,#dfe3e6)',BorderBottomColor:'#b9bec3'}),new Css.Rule('.ColorPickerWheel[theme="light"] .ColorPickerWheel-Input',{Background:'#fff',BorderColor:'#c1c6cb',Color:'#30363b'})
    ]);
    @Component('arianna-color-picker-wheel',Styles,{Shadow:false,Attributes:['value','theme']})
    export class ColorPickerWheel extends HTMLDivElement
    {public static readonly Styles=Styles;public template=html``;private _h=325;private _s=82;private _l=53;constructor(o:Interfaces.ColorPickerWheelOptions={}){super();if(o.theme)this.setAttribute('theme',o.theme);if(o.value)this.Set(o.value,false);}public onCreated(){requestAnimationFrame(()=>{if(this.isConnected)this.onConnected();});}public onConnected(){this.classList.add('ColorPickerWheel');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');const v=this.getAttribute('value');if(v)this.Set(v,false);this.Render();}private Set(v:string,emit=true){const p=parseHexRgba(v),h=rgbToHsl(p.r,p.g,p.b);this._h=h.h;this._s=h.s;this._l=h.l;if(emit)this.Emit();}public setValue(v:string):this{this.Set(v);return this;}public getValue():string{return this.Hex();}public onBeforeMount(){}public onMount(){}public onBeforeUpdate(){}public onUpdate(){}public onBeforeUnmount(){}public onUnmount(){}private Hex(){const c=hslToRgb(this._h,this._s,this._l);return rgbToHex(c.r,c.g,c.b);}private Emit(){this.setAttribute('value',this.Hex());this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{value:this.Hex()}}));}private Render(){this.style.setProperty('--color',this.Hex());const r=document.createElement('section'),h=document.createElement('header');h.className='ColorPickerWheel-Header';h.textContent='Color Wheel';const b=document.createElement('div');b.className='ColorPickerWheel-Body';const wheel=document.createElement('div');wheel.className='ColorPickerWheel-Wheel';const k=document.createElement('span');k.className='ColorPickerWheel-Knob';k.style.transform=`translateX(-50%) rotate(${this._h}deg)`;k.style.transformOrigin='50% 98px';wheel.append(k);wheel.onpointerdown=e=>{const q=wheel.getBoundingClientRect(),x=e.clientX-(q.left+q.width/2),y=e.clientY-(q.top+q.height/2);this._h=(Math.atan2(y,x)*180/Math.PI+90+360)%360;this.Emit();this.Render();};const f=document.createElement('div');f.className='ColorPickerWheel-Footer';const ch=document.createElement('div');ch.className='ColorPickerWheel-Chip';const i=document.createElement('div');i.className='ColorPickerWheel-Input';i.textContent=this.Hex();f.append(ch,i);b.append(wheel,f);r.append(h,b);this.replaceChildren(r);}}
}
export type ColorPickerWheelOptions=ColorPickerWheel.Interfaces.ColorPickerWheelOptions;export default ColorPickerWheel.ColorPickerWheel;
