/** @module components/graphics/colors/ColorPickerSquare */
import { Component, Css, Templates } from '../../../core/index.ts';
import { parseHexRgba, rgbToHex, rgbToHsl, hslToRgb } from './GraphicsColorPicker.ts';
const html=Templates.Template.Html;
export namespace ColorPickerSquare{
 export namespace Interfaces{export interface ColorPickerSquareOptions{value?:string;color?:string;theme?:'dark'|'light';}export interface HSVState{h:number;s:number;v:number;}}
 interface S{h:number;s:number;v:number;bound:boolean;}const M=new WeakMap<HTMLElement,S>();
 const clamp=(x:number)=>Math.max(0,Math.min(1,x));
 const state=(e:HTMLElement):S=>{let s=M.get(e);if(!s){const c=parseHexRgba(e.getAttribute('value')||'#93BEE6'),hsl=rgbToHsl(c.rgb);s={h:hsl.h,s:hsl.s/100,v:Math.max(.01,(hsl.l/100)*(1+hsl.s/100)),bound:false};M.set(e,s);}return s;};
 const hsvToRgb=(h:number,s:number,v:number)=>{const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let r=0,g=0,b=0;if(h<60){r=c;g=x}else if(h<120){r=x;g=c}else if(h<180){g=c;b=x}else if(h<240){g=x;b=c}else if(h<300){r=x;b=c}else{r=c;b=x}return{r:(r+m)*255,g:(g+m)*255,b:(b+m)*255};};
 export const Styles=new Css.Stylesheet([
  new Css.Rule('arianna-color-picker-square,.ColorPickerSquare',{Background:'#202428',Border:'1px solid #121517',BorderRadius:'8px',Color:'#e5e8ea',Display:'block',FontFamily:'var(--arianna-font,system-ui,sans-serif)',Overflow:'hidden',Width:'290px'}),new Css.Rule('.ColorPickerSquare-Head',{Background:'linear-gradient(180deg,#363b40,#282c30)',BorderBottom:'1px solid #111417',FontSize:'10px',FontWeight:'800',Padding:'8px 10px'}),new Css.Rule('.ColorPickerSquare-Body',{Display:'grid',Gap:'8px',Padding:'10px'}),new Css.Rule('.ColorPickerSquare-SV',{Background:'linear-gradient(to top,#000,transparent),linear-gradient(to right,#fff,transparent),hsl(var(--h),100%,50%)',Border:'1px solid #0f1214',BorderRadius:'4px',Cursor:'crosshair',Height:'170px',Position:'relative'}),new Css.Rule('.ColorPickerSquare-Cursor',{Border:'2px solid #fff',BorderRadius:'50%',BoxShadow:'0 0 0 1px #000',Height:'12px',Left:'0',Position:'absolute',Top:'0',Transform:'translate(-50%,-50%)',Width:'12px'}),new Css.Rule('.ColorPickerSquare-Hue',{AccentColor:'#e40c88',Width:'100%'}),new Css.Rule('.ColorPickerSquare-Row',{AlignItems:'center',Display:'grid',Gap:'6px',GridTemplateColumns:'36px 1fr'}),new Css.Rule('.ColorPickerSquare-Chip',{Border:'1px solid #111417',BorderRadius:'3px',Height:'28px'}),new Css.Rule('.ColorPickerSquare-Input',{Background:'#161a1d',Border:'1px solid #3a4046',BorderRadius:'3px',Color:'#e7eaec',Font:'9px ui-monospace,monospace',Padding:'6px'}),new Css.Rule('arianna-color-picker-square[theme="light"],.ColorPickerSquare[theme="light"]',{Background:'#f4f5f6',BorderColor:'#bbc1c6',Color:'#283039'}),new Css.Rule('arianna-color-picker-square[theme="light"] .ColorPickerSquare-Head',{Background:'linear-gradient(180deg,#fff,#e3e6e9)',BorderBottomColor:'#bbc1c6'}),new Css.Rule('arianna-color-picker-square[theme="light"] .ColorPickerSquare-Input',{Background:'#fff',BorderColor:'#c6cbd0',Color:'#30373d'})
 ]);
 @Component('arianna-color-picker-square',Styles,{Shadow:false,Attributes:['value','color','theme']}) export class ColorPickerSquare extends HTMLElement{
  public static readonly Styles=Styles;public template=html``;public onCreated():void{if(this.isConnected)this.onConnected();}public onConnected():void{this.classList.add('ColorPickerSquare');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');if(this.getAttribute('value')||this.getAttribute('color'))this.setColor(this.getAttribute('value')||this.getAttribute('color')||'#93BEE6');else this.render();}
  public setColor(hex:string):this{const c=parseHexRgba(hex),hsl=rgbToHsl(c.rgb),st=state(this);st.h=hsl.h;const l=hsl.l/100,ss=hsl.s/100;st.v=l+ss*Math.min(l,1-l);st.s=st.v===0?0:2*(1-l/st.v);this.setAttribute('value',c.hex);this.render();this.emit();return this;}public getColor():string{return rgbToHex(hsvToRgb(state(this).h,state(this).s,state(this).v));}
  private render():void{const s=state(this);this.style.setProperty('--h',String(s.h));this.style.setProperty('--s',String(s.s*100));this.style.setProperty('--v',String(s.v*100));const root=document.createElement('section');const h=document.createElement('header');h.className='ColorPickerSquare-Head';h.textContent='Color';const b=document.createElement('div');b.className='ColorPickerSquare-Body';const sv=document.createElement('div');sv.className='ColorPickerSquare-SV';const cur=document.createElement('span');cur.className='ColorPickerSquare-Cursor';cur.style.left=`${s.s*100}%`;cur.style.top=`${(1-s.v)*100}%`;sv.append(cur);const hue=document.createElement('input');hue.type='range';hue.min='0';hue.max='360';hue.value=String(Math.round(s.h));hue.className='ColorPickerSquare-Hue';const row=document.createElement('div');row.className='ColorPickerSquare-Row';const chip=document.createElement('span');chip.className='ColorPickerSquare-Chip';chip.style.background=this.getColor();const inp=document.createElement('input');inp.className='ColorPickerSquare-Input';inp.value=this.getColor();row.append(chip,inp);b.append(sv,hue,row);root.append(h,b);this.replaceChildren(root);sv.onpointerdown=e=>{const r=sv.getBoundingClientRect();s.s=clamp((e.clientX-r.left)/r.width);s.v=clamp(1-(e.clientY-r.top)/r.height);this.render();this.emit();};hue.oninput=()=>{s.h=Number(hue.value);this.render();this.emit();};inp.onchange=()=>this.setColor(inp.value);}
  private emit():void{const v=this.getColor();this.setAttribute('value',v);this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{value:v,source:this}}));}
 }
}
export type ColorPickerSquareOptions=ColorPickerSquare.Interfaces.ColorPickerSquareOptions;export default ColorPickerSquare.ColorPickerSquare;
