/** @module components/graphics/colors/ColorPickerTile */
import { Component, Css, Templates } from '../../../core/index.ts';
const html=Templates.Template.Html;
export namespace ColorPickerTile
{
    export namespace Interfaces{export interface ColorPickerTileOptions{value?:string;theme?:'dark'|'light';palette?:string[];}export interface TileState{selected:string;recent:string[];}}
    const P=['#E40C88','#F647A3','#F15B6C','#F28C3C','#F2C94C','#7EC850','#35B875','#2AA7A1','#25AFC3','#3489D8','#4F65D5','#6754D8','#9B5CF6','#B744CE','#D04BA5','#F1B3DC','#B7BDC3','#FFFFFF','#737A82','#25292D','#111315','#000000','#6A4C3B','#9B7B5A'];
    export const Styles=new Css.Stylesheet([
        new Css.Rule('.ColorPickerTile',{Background:'#202428',Border:'1px solid #121517',BorderRadius:'8px',BoxSizing:'border-box',Color:'#e5e8ea',Display:'block',FontFamily:'var(--arianna-font,system-ui,sans-serif)',Overflow:'hidden',Width:'300px'}),
        new Css.Rule('.ColorPickerTile-Header',{Background:'linear-gradient(180deg,#363b40,#25292d)',BorderBottom:'1px solid #111417',FontSize:'10px',FontWeight:'760',Padding:'8px 10px'}),
        new Css.Rule('.ColorPickerTile-Body',{Display:'grid',Gap:'9px',Padding:'10px'}),
        new Css.Rule('.ColorPickerTile-Current',{AlignItems:'center',Display:'grid',Gap:'8px',GridTemplateColumns:'42px 1fr'}),
        new Css.Rule('.ColorPickerTile-Preview',{Background:'var(--selected)',Border:'1px solid #101214',BorderRadius:'4px',Height:'32px'}),
        new Css.Rule('.ColorPickerTile-Value',{Background:'#181c20',Border:'1px solid #3b4147',BorderRadius:'4px',Color:'#e4e8eb',Font:'10px ui-monospace,monospace',Padding:'7px'}),
        new Css.Rule('.ColorPickerTile-Grid',{Display:'grid',Gap:'5px',GridTemplateColumns:'repeat(8,1fr)'}),
        new Css.Rule('.ColorPickerTile-Swatch',{Appearance:'none',Background:'var(--swatch)',Border:'1px solid rgba(255,255,255,.12)',BorderRadius:'4px',Cursor:'pointer',Height:'27px',Padding:'0',Position:'relative'}),
        new Css.Rule('.ColorPickerTile-Swatch[data-selected="true"]::after',{Border:'2px solid #fff',BorderRadius:'3px',BoxShadow:'0 0 0 1px #000',Content:'""',Inset:'3px',Position:'absolute'}),
        new Css.Rule('.ColorPickerTile[theme="light"]',{Background:'#eef0f2',BorderColor:'#b9bec3',Color:'#25292d'}),new Css.Rule('.ColorPickerTile[theme="light"] .ColorPickerTile-Header',{Background:'linear-gradient(180deg,#f9fafb,#dfe3e6)',BorderBottomColor:'#b9bec3'}),new Css.Rule('.ColorPickerTile[theme="light"] .ColorPickerTile-Value',{Background:'#fff',BorderColor:'#c1c6cb',Color:'#30363b'})
    ]);
    @Component('arianna-color-picker-tile',Styles,{Shadow:false,Attributes:['value','theme'],Properties:['palette']})
    export class ColorPickerTile extends HTMLDivElement
    {public static readonly Styles=Styles;public template=html``;private _palette=[...P];private _selected='#E40C88';constructor(o:Interfaces.ColorPickerTileOptions={}){super();if(o.theme)this.setAttribute('theme',o.theme);if(o.palette)this._palette=o.palette;if(o.value)this._selected=o.value;}public onCreated(){requestAnimationFrame(()=>{if(this.isConnected)this.onConnected();});}public onConnected(){this.classList.add('ColorPickerTile');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');this._selected=this.getAttribute('value')||this._selected;this.Render();}public get palette(){return this._palette;}public set palette(v:string[]){this._palette=Array.isArray(v)?v:[];this.Render();}public get value(){return this._selected;}public set value(v:string){this._selected=v;this.setAttribute('value',v);this.Render();}public setColor(hex:string):this{this.value=hex;return this;}public getColor():string{return this._selected;}public getRecent():string[]{return [this._selected,...this._palette.filter(x=>x!==this._selected)].slice(0,8);}public onBeforeMount(){}public onMount(){}public onBeforeUpdate(){}public onUpdate(){}public onBeforeUnmount(){}public onUnmount(){}private Pick(c:string){this._selected=c;this.setAttribute('value',c);this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{value:c}}));this.Render();}private Render(){this.style.setProperty('--selected',this._selected);const root=document.createElement('section');const h=document.createElement('header');h.className='ColorPickerTile-Header';h.textContent='Color Swatches';const body=document.createElement('div');body.className='ColorPickerTile-Body';const current=document.createElement('div');current.className='ColorPickerTile-Current';const prev=document.createElement('div');prev.className='ColorPickerTile-Preview';const val=document.createElement('div');val.className='ColorPickerTile-Value';val.textContent=this._selected;current.append(prev,val);const grid=document.createElement('div');grid.className='ColorPickerTile-Grid';for(const c of this._palette){const b=document.createElement('button');b.className='ColorPickerTile-Swatch';b.style.setProperty('--swatch',c);b.dataset.selected=String(c.toUpperCase()===this._selected.toUpperCase());b.onclick=()=>this.Pick(c);grid.append(b);}body.append(current,grid);root.append(h,body);this.replaceChildren(root);}}
}
export type ColorPickerTileOptions=ColorPickerTile.Interfaces.ColorPickerTileOptions;export default ColorPickerTile.ColorPickerTile;
