/** @module components/graphics/colors/ColorPickerTile */
import { Component, Css, Templates } from '../../../core/index.ts';import { parseHexRgba } from './GraphicsColorPicker.ts';const html=Templates.Template.Html;
export namespace ColorPickerTile{
 export namespace Interfaces{export interface ColorPickerTileOptions{value?:string;palette?:string[];theme?:'dark'|'light';}export interface TileState{value:string;recent:string[];}}
 const DEFAULT=['#E40C88','#6954D8','#3489D8','#35B875','#F0C84B','#F28A42','#E0525B','#F4F5F6','#252A2F','#A85DD6','#38C5B7','#74B84F','#E77DB7','#8C59C8','#2D72CC','#111315'];
 const M=new WeakMap<HTMLElement,{value:string;palette:string[];recent:string[]}>();const state=(e:HTMLElement)=>{let s=M.get(e);if(!s){s={value:e.getAttribute('value')||'#93BEE6',palette:[...DEFAULT],recent:[]};M.set(e,s);}return s;};
 export const Styles=new Css.Stylesheet([new Css.Rule('arianna-color-picker-tile,.ColorPickerTile',{Background:'#202428',Border:'1px solid #111417',BorderRadius:'8px',Color:'#e6e9eb',Display:'block',FontFamily:'var(--arianna-font,system-ui,sans-serif)',Overflow:'hidden',Width:'300px'}),new Css.Rule('.ColorPickerTile-Head',{Background:'linear-gradient(180deg,#373c41,#292e32)',BorderBottom:'1px solid #111417',FontSize:'10px',FontWeight:'800',Padding:'8px 10px'}),new Css.Rule('.ColorPickerTile-Body',{Display:'grid',Gap:'8px',Padding:'10px'}),new Css.Rule('.ColorPickerTile-Selected',{Border:'1px solid #111417',BorderRadius:'5px',Height:'72px'}),new Css.Rule('.ColorPickerTile-Grid',{Display:'grid',Gap:'5px',GridTemplateColumns:'repeat(8,1fr)'}),new Css.Rule('.ColorPickerTile-Swatch',{Appearance:'none',Border:'1px solid rgba(255,255,255,.22)',BorderRadius:'4px',Cursor:'pointer',Height:'27px'}),new Css.Rule('.ColorPickerTile-Swatch[data-selected="true"]',{BoxShadow:'0 0 0 2px #e40c88'}),new Css.Rule('.ColorPickerTile-Value',{Background:'#171b1f',Border:'1px solid #3a4046',BorderRadius:'3px',Color:'#e5e8ea',Font:'9px ui-monospace,monospace',Padding:'6px'}),new Css.Rule('arianna-color-picker-tile[theme="light"],.ColorPickerTile[theme="light"]',{Background:'#f4f5f6',BorderColor:'#bac0c5',Color:'#283039'}),new Css.Rule('arianna-color-picker-tile[theme="light"] .ColorPickerTile-Head',{Background:'linear-gradient(180deg,#fff,#e3e6e9)',BorderBottomColor:'#bac0c5'}),new Css.Rule('arianna-color-picker-tile[theme="light"] .ColorPickerTile-Value',{Background:'#fff',BorderColor:'#c5cbd0',Color:'#30373d'})]);
 @Component('arianna-color-picker-tile',Styles,{Shadow:false,Attributes:['value','theme'],Properties:['palette']})export class ColorPickerTile extends HTMLElement{
  public static readonly Styles=Styles;public template=html``;public onCreated():void{if(this.isConnected)this.onConnected();}public onConnected():void{this.classList.add('ColorPickerTile');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');this.render();}
  public get palette():string[]{return[...state(this).palette];}public set palette(v:string[]){state(this).palette=Array.isArray(v)&&v.length?[...v]:[...DEFAULT];this.render();}public get value():string{return state(this).value;}public set value(v:string){this.setColor(v);}public setColor(hex:string):this{const v=parseHexRgba(hex).hex,s=state(this);s.value=v;s.recent=[v,...s.recent.filter(x=>x!==v)].slice(0,8);this.setAttribute('value',v);this.render();this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{value:v,source:this}}));return this;}public getColor():string{return this.value;}public getRecent():string[]{return[...state(this).recent];}
  private render():void{const s=state(this),root=document.createElement('section'),h=document.createElement('header');h.className='ColorPickerTile-Head';h.textContent='Swatches';const b=document.createElement('div');b.className='ColorPickerTile-Body';const sel=document.createElement('div');sel.className='ColorPickerTile-Selected';sel.style.background=s.value;const grid=document.createElement('div');grid.className='ColorPickerTile-Grid';s.palette.forEach(c=>{const x=document.createElement('button');x.className='ColorPickerTile-Swatch';x.style.background=c;x.dataset.selected=String(parseHexRgba(c).hex===s.value);x.onclick=()=>this.setColor(c);grid.append(x);});const inp=document.createElement('input');inp.className='ColorPickerTile-Value';inp.value=s.value;inp.onchange=()=>this.setColor(inp.value);b.append(sel,grid,inp);root.append(h,b);this.replaceChildren(root);}
 }
}
export type ColorPickerTileOptions=ColorPickerTile.Interfaces.ColorPickerTileOptions;export default ColorPickerTile.ColorPickerTile;
