/** @module components/graphics/colors/ColorPickerWheel */
import { Component, Css, Templates } from '../../../core/index.ts';import { parseHexRgba,rgbToHsl,rgbToHex,hslToRgb } from './GraphicsColorPicker.ts';const html=Templates.Template.Html;
export namespace ColorPickerWheel{
 export namespace Interfaces{export interface ColorPickerWheelOptions{value?:string;color?:string;theme?:'dark'|'light';}}
 const M=new WeakMap<HTMLElement,{h:number;s:number;l:number}>();const st=(e:HTMLElement)=>{let s=M.get(e);if(!s){const c=parseHexRgba(e.getAttribute('value')||'#E40C88');s=rgbToHsl(c.rgb);M.set(e,s);}return s;};
 export const Styles=new Css.Stylesheet([new Css.Rule('arianna-color-picker-wheel,.ColorPickerWheel',{Background:'#202428',Border:'1px solid #111417',BorderRadius:'8px',Color:'#e7eaec',Display:'block',FontFamily:'var(--arianna-font,system-ui,sans-serif)',Overflow:'hidden',Width:'300px'}),new Css.Rule('.ColorPickerWheel-Head',{Background:'linear-gradient(180deg,#383d42,#292e32)',BorderBottom:'1px solid #111417',FontSize:'10px',FontWeight:'800',Padding:'8px 10px'}),new Css.Rule('.ColorPickerWheel-Body',{Display:'grid',Gap:'9px',Padding:'12px'}),new Css.Rule('.ColorPickerWheel-Wheel',{Background:'radial-gradient(circle,#fff 0,rgba(255,255,255,0) 68%),conic-gradient(#f00,#ff0,#0f0,#0ff,#00f,#f0f,#f00)',Border:'1px solid #101214',BorderRadius:'50%',Cursor:'crosshair',Height:'220px',Margin:'0 auto',Position:'relative',Width:'220px'}),new Css.Rule('.ColorPickerWheel-Cursor',{Border:'2px solid #fff',BorderRadius:'50%',BoxShadow:'0 0 0 1px #000',Height:'12px',Position:'absolute',Transform:'translate(-50%,-50%)',Width:'12px'}),new Css.Rule('.ColorPickerWheel-Light',{AccentColor:'#e40c88',Width:'100%'}),new Css.Rule('.ColorPickerWheel-Value',{Background:'#171b1f',Border:'1px solid #3a4046',BorderRadius:'3px',Color:'#e7eaec',Font:'9px ui-monospace,monospace',Padding:'6px'}),new Css.Rule('arianna-color-picker-wheel[theme="light"],.ColorPickerWheel[theme="light"]',{Background:'#f4f5f6',BorderColor:'#bac0c5',Color:'#283039'}),new Css.Rule('arianna-color-picker-wheel[theme="light"] .ColorPickerWheel-Head',{Background:'linear-gradient(180deg,#fff,#e3e6e9)',BorderBottomColor:'#bac0c5'}),new Css.Rule('arianna-color-picker-wheel[theme="light"] .ColorPickerWheel-Value',{Background:'#fff',BorderColor:'#c5cbd0',Color:'#30373d'})]);
 @Component('arianna-color-picker-wheel',Styles,{Shadow:false,Attributes:['value','color','theme']})export class ColorPickerWheel extends HTMLElement{
  public static readonly Styles=Styles;public template=html``;public onCreated():void{if(this.isConnected)this.onConnected();}public onConnected():void{this.classList.add('ColorPickerWheel');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');this.render();}public setValue(v:string):this{const c=parseHexRgba(v),s=rgbToHsl(c.rgb);M.set(this,s);this.setAttribute('value',c.hex);this.render();this.emit();return this;}public getValue():string{return rgbToHex(hslToRgb(st(this)));}
  private render():void{const s=st(this),root=document.createElement('section'),h=document.createElement('header');h.className='ColorPickerWheel-Head';h.textContent='Color Wheel';const b=document.createElement('div');b.className='ColorPickerWheel-Body';const w=document.createElement('div');w.className='ColorPickerWheel-Wheel';const c=document.createElement('span');c.className='ColorPickerWheel-Cursor';const r=(s.s/100)*.44,ang=(s.h-90)*Math.PI/180;c.style.left=`${50+Math.cos(ang)*r*100}%`;c.style.top=`${50+Math.sin(ang)*r*100}%`;w.append(c);const l=document.createElement('input');l.type='range';l.min='0';l.max='100';l.value=String(Math.round(s.l));l.className='ColorPickerWheel-Light';const inp=document.createElement('input');inp.className='ColorPickerWheel-Value';inp.value=this.getValue();b.append(w,l,inp);root.append(h,b);this.replaceChildren(root);w.onpointerdown=e=>{const q=w.getBoundingClientRect(),x=e.clientX-(q.left+q.width/2),y=e.clientY-(q.top+q.height/2),rad=Math.sqrt(x*x+y*y)/(q.width/2);s.s=Math.min(100,rad*100);s.h=(Math.atan2(y,x)*180/Math.PI+90+360)%360;this.render();this.emit();};l.oninput=()=>{s.l=Number(l.value);this.render();this.emit();};inp.onchange=()=>this.setValue(inp.value);}
  private emit():void{const v=this.getValue();this.setAttribute('value',v);this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{value:v,source:this}}));}
 }
}
export type ColorPickerWheelOptions=ColorPickerWheel.Interfaces.ColorPickerWheelOptions;export default ColorPickerWheel.ColorPickerWheel;
