import HSVColorPicker from './HSVColorPicker.ts';
import {lineAngle,projectOnLine,type GradientLine} from './PickerGeometry.ts';
/** Gradient interaction engine. Stops retain identity while crossing and controls survive pointermove. */
import {Templates} from '../../../core/index.ts';
import {DEFAULT_STOPS,sortStops,stopsToCss,sampleAt,colorFieldHex,type GradientStop,type RGBA} from './GradientEditor.ts';
import {parseHex} from '../../../additionals/graphics/Colors.ts';
import {PickerStyles,installPickerStyle,el,button,select,unit,finite,PickerGesture} from './PickerUI.ts';
export type GradientMode='linear'|'radial'|'shape';
export type Interpolation='srgb'|'oklab'|'oklch'|'hsl';
export interface ShapePoint{x:number;y:number;color:RGBA;radius?:number;}
const defaults=():ShapePoint[]=>[{x:.2,y:.25,color:{r:228,g:12,b:136,a:1},radius:.6},{x:.8,y:.25,color:{r:95,g:91,b:232,a:1},radius:.65},{x:.6,y:.8,color:{r:255,g:173,b:99,a:1},radius:.6}];
interface UI{preview:HTMLElement;canvas:HTMLCanvasElement;handle:HTMLElement;ramp:HTMLElement;stops:Map<GradientStop,HTMLButtonElement>;points:Map<ShapePoint,HTMLButtonElement>;fields:Map<string,HTMLInputElement|HTMLSelectElement>;color:HTMLInputElement;hex:HTMLInputElement;del:HTMLButtonElement;css:HTMLTextAreaElement;tabs:Map<string,HTMLButtonElement>;lineLayer:SVGSVGElement;linePath:SVGLineElement;lineHit:SVGLineElement;ends:HTMLButtonElement[];lineStops:Map<GradientStop,HTMLButtonElement>;directions:HTMLElement;}
interface State{mode?:GradientMode;stops:GradientStop[];selected:GradientStop;points:ShapePoint[];point:ShapePoint;ui?:UI;raf:number;emit:boolean;gesture:PickerGesture;angle:number;cx:number;cy:number;shape:'circle'|'ellipse';size:string;interp:Interpolation;internal:boolean;line:GradientLine;closeColor?:()=>void;resize?:ResizeObserver;}
const states=new WeakMap<object,State>();
function state(o:object):State{let s=states.get(o);if(!s){const stops=DEFAULT_STOPS(),points=defaults();s={stops,selected:stops[0],points,point:points[0],raf:0,emit:false,gesture:new PickerGesture(),angle:90,cx:50,cy:50,shape:'ellipse',size:'farthest-corner',interp:'srgb',internal:false,line:{start:{x:.12,y:.5},end:{x:.88,y:.5}}};states.set(o,s);}return s;}
const rgba=(c:RGBA)=>`rgba(${Math.round(c.r)},${Math.round(c.g)},${Math.round(c.b)},${unit(c.a)})`;
export abstract class GradientPickerBase extends HTMLElement{
 public static readonly Styles=PickerStyles;
 private reflectAttribute(name:string,value:string):void{if(this.getAttribute(name)!==value)this.setAttribute(name,value);}
 public template=Templates.Template.Html``;
 protected abstract get DefaultMode():GradientMode;
 public get mode():GradientMode{return state(this).mode||this.DefaultMode;}
 public set mode(v:GradientMode){if(!['linear','radial','shape'].includes(v))return;const s=state(this);s.closeColor?.();s.mode=v;s.gesture.cancel();this.changed();}
 public onCreated():void{if(this.isConnected)this.onConnected();}
 public onConnected():void{installPickerStyle(this);for(const n of ['angle','cx','cy','shape','size','interp','interpolation'])this.read(n);this.render();const s=state(this);if(!s.resize&&typeof ResizeObserver!=='undefined'){s.resize=new ResizeObserver(()=>this.render());s.resize.observe(s.ui!.preview);}}
 public onDisconnected():void{const s=state(this);s.gesture.cancel();s.closeColor?.();s.resize?.disconnect();s.resize=undefined;if(s.raf)cancelAnimationFrame(s.raf);s.raf=0;s.emit=false;}
 public onAttributeChanged(n:string):void{if(state(this).internal)return;this.read(n);if(this.isConnected)this.render();}
 private read(n:string):void{if(!this.hasAttribute(n))return;const s=state(this),v=this.getAttribute(n)!;if(n==='angle'){s.angle=((finite(+v,90)%360)+360)%360;this.orientLine();}if(n==='cx'||n==='cy')s[n]=unit(+v/100)*100;if(n==='shape'&&(v==='circle'||v==='ellipse'))s.shape=v;if(n==='size'&&['closest-side','farthest-side','closest-corner','farthest-corner'].includes(v))s.size=v;if((n==='interp'||n==='interpolation')&&['srgb','oklab','oklch','hsl'].includes(v))s.interp=v as Interpolation;}
 private attr(k:string,v:string):void{const s=state(this);s.internal=true;try{this.reflectAttribute(k,v);}finally{s.internal=false;}this.changed();}
 public get stops():GradientStop[]{return sortStops(state(this).stops);}
 public set stops(v:GradientStop[]){const s=state(this);s.stops=sortStops(v?.length?v:DEFAULT_STOPS());if(s.stops.length===1)s.stops.push({...s.stops[0],t:1,color:{...s.stops[0].color}});s.selected=s.stops[0];this.changed();}
 public setStops(v:GradientStop[]):this{this.stops=v;return this;}
 public getStops():GradientStop[]{return this.stops;}
 public getAngle():number{return state(this).angle;}
 public setAngle(v:number):this{const s=state(this);s.angle=((finite(v,90)%360)+360)%360;this.orientLine();this.attr('angle',String(s.angle));return this;}
 public getInterp():Interpolation{return state(this).interp;}
 public setInterp(v:Interpolation):this{if(!['srgb','oklab','oklch','hsl'].includes(v))return this;state(this).interp=v;this.attr('interp',v);return this;}
 public getShape():'circle'|'ellipse'{return state(this).shape;}
 public setShape(v:'circle'|'ellipse'):this{state(this).shape=v;this.attr('shape',v);return this;}
 public getSize():'closest-side'|'farthest-side'|'closest-corner'|'farthest-corner'{return state(this).size as ReturnType<GradientPickerBase['getSize']>;}
 public setSize(v:ReturnType<GradientPickerBase['getSize']>):this{state(this).size=v;this.attr('size',v);return this;}
 public getCenter():{cx:number;cy:number}{return{cx:state(this).cx,cy:state(this).cy};}
 public setCenter(cx:number,cy:number):this{const s=state(this);s.cx=unit(cx/100)*100;s.cy=unit(cy/100)*100;s.internal=true;try{this.reflectAttribute('cx',String(s.cx));this.reflectAttribute('cy',String(s.cy));}finally{s.internal=false;}this.changed();return this;}
 public get points():ShapePoint[]{return structuredClone(state(this).points);}
 public set points(v:ShapePoint[]){const s=state(this);s.points=(v?.length?v:defaults()).map(p=>({x:unit(p.x),y:unit(p.y),radius:Math.max(.02,finite(p.radius??.6,.6)),color:{r:Math.max(0,Math.min(255,finite(p.color.r))),g:Math.max(0,Math.min(255,finite(p.color.g))),b:Math.max(0,Math.min(255,finite(p.color.b))),a:unit(p.color.a)}}));s.point=s.points[0];this.changed();}
 public addPoint(x:number,y:number,c:RGBA):ShapePoint{const s=state(this),p={x:unit(x),y:unit(y),color:{...c},radius:.6};s.points.push(p);s.point=p;this.changed();return structuredClone(p);}
 public removePoint(i:number):this{const s=state(this);if(s.points.length>1&&i>=0&&i<s.points.length){s.points.splice(i,1);s.point=s.points[Math.min(i,s.points.length-1)];this.changed();}return this;}
 public updatePoint(i:number,patch:Partial<ShapePoint>):this{const s=state(this),p=s.points[i];if(p){if(patch.x!=null)p.x=unit(patch.x);if(patch.y!=null)p.y=unit(patch.y);if(patch.radius!=null)p.radius=Math.max(.02,finite(patch.radius,.6));if(patch.color)p.color={...patch.color,a:unit(patch.color.a)};this.changed();}return this;}
 public setPoints(v:ShapePoint[]):this{this.points=v;return this;}
 public getPoints():ShapePoint[]{return this.points;}
 public toCSS():string{const s=state(this),i=s.interp==='srgb'?'':` in ${s.interp}`;if(this.mode==='shape')return [...s.points].reverse().map(p=>`radial-gradient(circle at ${p.x*100}% ${p.y*100}%,${rgba(p.color)} 0%,transparent ${Math.min(100,(p.radius??.6)*100)}%)`).join(',');if(this.mode==='radial')return `radial-gradient(${s.shape} ${s.size} at ${s.cx}% ${s.cy}%${i},${stopsToCss(s.stops)})`;const r=s.ui?.preview.getBoundingClientRect(),w=r?.width||360,h=r?.height||240,a=s.angle*Math.PI/180,dx=Math.sin(a),dy=-Math.cos(a),length=Math.abs(w*dx)+Math.abs(h*dy)||1,at=(p:{x:number;y:number})=>.5+((p.x-.5)*w*dx+(p.y-.5)*h*dy)/length,from=at(s.line.start),to=at(s.line.end);return `linear-gradient(${s.angle}deg${i},${stopsToCss(s.stops.map(p=>({...p,t:from+(to-from)*p.t})))})`;}
 public toCanvasDataURL(type='image/png'):string{this.render();this.paintShape();return state(this).ui?.canvas.toDataURL(type)||'';}
 private changed():void{const s=state(this);s.emit=true;if(this.isConnected)this.render();this.schedule();}
 private schedule():void{const s=state(this);if(s.raf)return;s.raf=requestAnimationFrame(()=>{s.raf=0;if(!this.isConnected)return;if(this.mode==='shape')this.paintShape();if(s.emit){s.emit=false;this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{type:this.mode,stops:this.getStops(),points:this.getPoints(),angle:s.angle,center:this.getCenter(),shape:s.shape,size:s.size,interpolation:s.interp,css:this.toCSS(),source:this}}));}});}
 public getLine():GradientLine{return structuredClone(state(this).line);}
 public setLine(line:GradientLine):this{const s=state(this),r=s.ui?.preview.getBoundingClientRect();const next={start:{x:unit(line.start.x),y:unit(line.start.y)},end:{x:unit(line.end.x),y:unit(line.end.y)}};if(Math.hypot(next.end.x-next.start.x,next.end.y-next.start.y)<.005)return this;s.line=next;s.angle=lineAngle(next,r?.width||360,r?.height||240);this.attr('angle',String(s.angle));return this;}
 private orientLine():void{const s=state(this),r=s.ui?.preview.getBoundingClientRect(),w=r?.width||360,h=r?.height||240,a=s.angle*Math.PI/180,dx=Math.sin(a)/w,dy=-Math.cos(a)/h,k=.38/Math.max(Math.abs(dx),Math.abs(dy),1e-9);s.line={start:{x:.5-dx*k,y:.5-dy*k},end:{x:.5+dx*k,y:.5+dy*k}};}
 private openColor(target:GradientStop|ShapePoint,anchor:HTMLElement):void{
  const s=state(this);s.closeColor?.();
  const popup=el('div','ac-modern cp-popover');popup.setAttribute('theme',this.getAttribute('theme')||'dark');popup.setAttribute('popover','auto');popup.setAttribute('role','dialog');popup.setAttribute('aria-label','Edit selected colour');
  const bar=el('header','cp-popover-bar'),picker=new HSVColorPicker();picker.geometry='ring';picker.setAttribute('theme',this.getAttribute('theme')||'dark');picker.setColor(target.color);
  let closed=false;const commit=()=>{const c=picker.getColor();target.color={r:c.r,g:c.g,b:c.b,a:c.a??1};this.changed();};
  const outside=(e:Event)=>{if(!popup.contains(e.target as Node)&&e.target!==anchor)close();};
  const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close();anchor.focus();}};
  const close=()=>{if(closed)return;closed=true;commit();document.removeEventListener('pointerdown',outside,{capture:true});document.removeEventListener('keydown',key,{capture:true});s.closeColor=undefined;popup.remove();};
  s.closeColor=close;bar.append(el('strong','','Colour'),button('Done',()=>{close();anchor.focus();}));popup.append(bar,picker);this.appendChild(popup);
  picker.addEventListener('arianna:change',e=>{e.stopPropagation();if(!closed)commit();});
  const r=anchor.getBoundingClientRect(),width=Math.min(310,window.innerWidth-24);popup.style.width=width+'px';popup.style.left=Math.max(12,Math.min(window.innerWidth-width-12,r.left))+'px';popup.style.top=Math.max(12,Math.min(r.bottom+8,window.innerHeight-520))+'px';
  if(typeof popup.showPopover==='function'){popup.addEventListener('toggle',(e:Event)=>{if((e as ToggleEvent).newState==='closed')close();});popup.showPopover();}else document.addEventListener('pointerdown',outside,{capture:true});
  document.addEventListener('keydown',key,{capture:true});
 }
 private addStop(t:number):void{const s=state(this),stop={t:unit(t),color:sampleAt(s.stops,t,s.interp)};s.stops.push(stop);s.stops.sort((a,b)=>a.t-b.t);s.selected=stop;this.changed();}
 private build():UI{const s=state(this),root=el('section'),head=el('header','cp-head');head.append(el('strong','','Gradient Studio'));const tabs=el('div','cp-tabs'),tabmap=new Map<string,HTMLButtonElement>();tabs.setAttribute('role','tablist');for(const m of ['linear','radial','shape'] as GradientMode[]){const b=button(m[0].toUpperCase()+m.slice(1),()=>this.mode=m);b.setAttribute('role','tab');tabs.appendChild(b);tabmap.set(m,b);}const body=el('div','cp-body'),preview=el('div','cp-preview'),canvas=el('canvas');canvas.width=360;canvas.height=240;const handle=el('span','cp-dot');preview.append(canvas,handle);preview.onpointerdown=e=>{if((e.target as HTMLElement).closest('.cp-point,.cp-line-stop,.cp-line-end,.cp-line-layer'))return;if(this.mode==='shape')return;s.gesture.start(e,preview,p=>{const r=preview.getBoundingClientRect(),x=unit((p.clientX-r.left)/r.width),y=unit((p.clientY-r.top)/r.height);if(this.mode==='radial')this.setCenter(x*100,y*100);else this.setAngle(Math.atan2(y-.5,x-.5)*180/Math.PI+90);});};preview.ondblclick=e=>{if(this.mode!=='shape'||(e.target as Element).closest('.cp-point'))return;const r=preview.getBoundingClientRect();this.addPoint((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height,{r:255,g:255,b:255,a:1});};
 const svg=(tag:string)=>document.createElementNS('http://www.w3.org/2000/svg',tag);
 const lineLayer=svg('svg') as SVGSVGElement;lineLayer.setAttribute('class','cp-line-layer');lineLayer.setAttribute('viewBox','0 0 100 100');lineLayer.setAttribute('preserveAspectRatio','none');
 const lineHit=svg('line') as SVGLineElement,linePath=svg('line') as SVGLineElement;lineHit.setAttribute('class','cp-line-hit');linePath.setAttribute('class','cp-line-path');linePath.setAttribute('vector-effect','non-scaling-stroke');lineHit.setAttribute('vector-effect','non-scaling-stroke');lineLayer.append(lineHit,linePath);preview.appendChild(lineLayer);
 const ends=['start','end'].map(key=>{const b=button('',()=>{});b.className='cp-line-end';b.setAttribute('aria-label',key==='start'?'Gradient line start':'Gradient line end');b.title=key==='start'?'Move gradient start · double-click for colour':'Move gradient end · double-click for colour';b.ondblclick=e=>{e.stopPropagation();const stop=key==='start'?s.stops[0]:s.stops[s.stops.length-1];s.selected=stop;this.openColor(stop,b);};b.onpointerdown=e=>{e.stopPropagation();s.gesture.start(e,b,p=>{const r=preview.getBoundingClientRect(),next=this.getLine();next[key as 'start'|'end']={x:unit((p.clientX-r.left)/r.width),y:unit((p.clientY-r.top)/r.height)};this.setLine(next);});};b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const next=this.getLine(),p=next[key as 'start'|'end'];p.x+=e.key==='ArrowRight'?.01:e.key==='ArrowLeft'?-.01:0;p.y+=e.key==='ArrowDown'?.01:e.key==='ArrowUp'?-.01:0;this.setLine(next);};preview.appendChild(b);return b;});
 lineHit.onpointerdown=e=>{e.stopPropagation();const r=preview.getBoundingClientRect(),base=this.getLine(),x=e.clientX,y=e.clientY;s.gesture.start(e,preview,p=>{const dx=Math.max(-Math.min(base.start.x,base.end.x),Math.min(1-Math.max(base.start.x,base.end.x),(p.clientX-x)/r.width)),dy=Math.max(-Math.min(base.start.y,base.end.y),Math.min(1-Math.max(base.start.y,base.end.y),(p.clientY-y)/r.height));this.setLine({start:{x:base.start.x+dx,y:base.start.y+dy},end:{x:base.end.x+dx,y:base.end.y+dy}});});};
 lineHit.ondblclick=e=>{e.stopPropagation();const r=preview.getBoundingClientRect();this.addStop(projectOnLine((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height,s.line,r.width,r.height));};
 const directions=el('div','cp-directions');directions.setAttribute('aria-label','Direction / radial extent origin');for(const [label,angle,x,y]of [['→',90,.2,.5],['←',270,.8,.5],['↓',180,.5,.2],['↑',0,.5,.8],['↘',135,.2,.2],['↗',45,.2,.8]] as [string,number,number,number][]){const b=button(label,()=>{if(this.mode==='radial')this.setCenter(x*100,y*100);else this.setAngle(angle);});b.dataset.angle=String(angle);b.dataset.cx=String(x*100);b.dataset.cy=String(y*100);b.title=this.mode==='radial'?'Radial direction '+label:'Gradient direction '+label;b.setAttribute('aria-label','Direction '+label);directions.appendChild(b);}
 const ramp=el('div','cp-ramp');ramp.onclick=e=>{if((e.target as Element).closest('.cp-stop'))return;const r=ramp.getBoundingClientRect();this.addStop((e.clientX-r.left)/r.width);};
 const fields=new Map<string,HTMLInputElement|HTMLSelectElement>(),area=el('div','cp-fields');const number=(key:string,label:string,min:number,max:number,step:number,fn:(n:number)=>void)=>{const l=el('label','',label),n=el('input');n.type='number';n.min=String(min);n.max=String(max);n.step=String(step);n.onchange=()=>fn(Number(n.value));l.appendChild(n);area.appendChild(l);fields.set(key,n);};number('angle','Angle °',0,360,.1,v=>this.setAngle(v));number('cx','Center X %',0,100,.1,v=>this.setCenter(v,s.cy));number('cy','Center Y %',0,100,.1,v=>this.setCenter(s.cx,v));number('position','Stop position %',0,100,.1,v=>{s.selected.t=unit(v/100);s.stops.sort((a,b)=>a.t-b.t);this.changed();});number('alpha','Opacity %',0,100,.1,v=>{(this.mode==='shape'?s.point:s.selected).color.a=unit(v/100);this.changed();});number('radius','Radius %',2,200,1,v=>{s.point.radius=Math.max(.02,v/100);this.changed();});number('x','Point X %',0,100,.1,v=>{s.point.x=unit(v/100);this.changed();});number('y','Point Y %',0,100,.1,v=>{s.point.y=unit(v/100);this.changed();});
 for(const [key,label,values,value,fn] of [['interp','Interpolation',['srgb','oklab','oklch','hsl'],s.interp,(v:string)=>this.setInterp(v as Interpolation)],['shape','Shape',['circle','ellipse'],s.shape,(v:string)=>this.setShape(v as 'circle'|'ellipse')],['size','Extent',['closest-side','farthest-side','closest-corner','farthest-corner'],s.size,(v:string)=>this.setSize(v as ReturnType<GradientPickerBase['getSize']>)]] as [string,string,string[],string,(v:string)=>void][]){const l=el('label','',label),n=select(values,value,fn);l.appendChild(n);area.appendChild(l);fields.set(key,n);}
 const edit=el('div','cp-row'),color=el('input'),hex=el('input','cp-hex');color.type='color';color.setAttribute('aria-label','Selected colour');hex.setAttribute('aria-label','Selected colour HEX');const set=(raw:string)=>{const c=parseHex(raw);if(!c)return;const target=this.mode==='shape'?s.point:s.selected;target.color={r:c.r,g:c.g,b:c.b,a:raw.length===9?c.a??1:target.color.a};this.changed();};color.oninput=()=>set(color.value);hex.onchange=()=>set(hex.value);const del=button('Delete',()=>{if(this.mode==='shape'){this.removePoint(s.points.indexOf(s.point));return;}if(s.stops.length>2){s.stops.splice(s.stops.indexOf(s.selected),1);s.selected=s.stops[0];this.changed();}});edit.append(color,hex,del);const css=el('textarea','cp-css');css.readOnly=true;css.setAttribute('aria-label','CSS gradient');const hint=el('p','cp-hint','Drag preview to orient / position. Click ramp to add stops. Double-click a stop to open its colour picker. Double-click Shape background to add a point. Arrow keys move handles; Delete removes them.');body.append(preview,directions,ramp,area,edit,css,hint);root.append(head,tabs,body);this.replaceChildren(root);return{preview,canvas,handle,ramp,stops:new Map(),points:new Map(),fields,color,hex,del,css,tabs:tabmap,lineLayer,linePath,lineHit,ends,lineStops:new Map(),directions};}
 private render():void{if(!this.isConnected)return;const s=state(this),ui=s.ui??(s.ui=this.build()),shape=this.mode==='shape';for(const [m,b]of ui.tabs)b.setAttribute('aria-selected',String(m===this.mode));ui.preview.style.background=shape?'transparent':this.toCSS();ui.canvas.hidden=!shape;ui.handle.hidden=this.mode!=='radial';ui.directions.hidden=shape;for(const child of Array.from(ui.directions.children)){const b=child as HTMLButtonElement;b.setAttribute('aria-pressed',String(this.mode==='linear'?Math.abs(s.angle-Number(b.dataset.angle))<.1:Math.abs(s.cx-Number(b.dataset.cx))<.1&&Math.abs(s.cy-Number(b.dataset.cy))<.1));}ui.ramp.hidden=shape;ui.handle.style.left=`${this.mode==='radial'?s.cx:50+Math.sin(s.angle*Math.PI/180)*40}%`;ui.handle.style.top=`${this.mode==='radial'?s.cy:50-Math.cos(s.angle*Math.PI/180)*40}%`;ui.ramp.style.background=`linear-gradient(90deg${s.interp==='srgb'?'':` in ${s.interp}`},${stopsToCss(s.stops)})`;
 for(const [stop,b]of ui.stops)if(!s.stops.includes(stop)){b.remove();ui.stops.delete(stop);}for(const stop of s.stops){let b=ui.stops.get(stop);if(!b){b=button('',()=>{s.selected=stop;this.render();});b.className='cp-stop';b.setAttribute('aria-label','Gradient stop; double-click to edit colour');b.ondblclick=e=>{e.stopPropagation();this.openColor(stop,b!);};b.onpointerdown=e=>{e.stopPropagation();s.selected=stop;s.gesture.start(e,b!,p=>{const r=ui.ramp.getBoundingClientRect();stop.t=unit((p.clientX-r.left)/r.width);s.stops.sort((a,b)=>a.t-b.t);this.changed();});};b.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();this.openColor(stop,b!);}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();stop.t=unit(stop.t+(e.key==='ArrowLeft'?-1:1)*(e.shiftKey?.1:.01));s.stops.sort((a,b)=>a.t-b.t);this.changed();}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();s.selected=stop;ui.del.click();}};ui.ramp.appendChild(b);ui.stops.set(stop,b);}b.style.left=`${stop.t*100}%`;b.style.setProperty('--color',rgba(stop.color));b.setAttribute('aria-pressed',String(s.selected===stop));b.title=`${Math.round(stop.t*100)}%`;}
 for(const [p,b]of ui.points)if(!s.points.includes(p)){b.remove();ui.points.delete(p);}for(const p of s.points){let b=ui.points.get(p);if(!b){b=button('',()=>{s.point=p;this.render();});b.className='cp-point';b.setAttribute('aria-label','Shape colour point; double-click to edit colour');b.ondblclick=e=>{e.stopPropagation();this.openColor(p,b!);};b.onpointerdown=e=>{e.stopPropagation();s.point=p;s.gesture.start(e,b!,ev=>{const r=ui.preview.getBoundingClientRect();p.x=unit((ev.clientX-r.left)/r.width);p.y=unit((ev.clientY-r.top)/r.height);this.changed();});};b.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();this.openColor(p,b!);}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();p.x=unit(p.x+(e.key==='ArrowRight'?.01:e.key==='ArrowLeft'?-.01:0));p.y=unit(p.y+(e.key==='ArrowDown'?.01:e.key==='ArrowUp'?-.01:0));this.changed();}else if(e.key==='Delete'){e.preventDefault();this.removePoint(s.points.indexOf(p));}};ui.preview.appendChild(b);ui.points.set(p,b);}b.hidden=!shape;b.style.left=`${p.x*100}%`;b.style.top=`${p.y*100}%`;b.style.setProperty('--color',rgba(p.color));b.setAttribute('aria-pressed',String(p===s.point));}
 const linear=this.mode==='linear',line=s.line;ui.lineLayer.style.display=linear?'':'none';
 for(const path of [ui.linePath,ui.lineHit]){path.setAttribute('x1',String(line.start.x*100));path.setAttribute('y1',String(line.start.y*100));path.setAttribute('x2',String(line.end.x*100));path.setAttribute('y2',String(line.end.y*100));}
 ui.ends.forEach((b,i)=>{b.hidden=!linear;const p=i?line.end:line.start;b.style.background=rgba((i?s.stops[s.stops.length-1]:s.stops[0]).color);b.style.left=`${p.x*100}%`;b.style.top=`${p.y*100}%`;});
 for(const [stop,b]of ui.lineStops)if(!s.stops.includes(stop)){b.remove();ui.lineStops.delete(stop);}
 for(const stop of s.stops){let b=ui.lineStops.get(stop);if(!b){b=button('',()=>{s.selected=stop;this.render();});b.className='cp-line-stop';b.title='Drag stop · double-click for colour';b.setAttribute('aria-label','Gradient line stop');b.ondblclick=e=>{e.stopPropagation();s.selected=stop;this.openColor(stop,b!);};b.onpointerdown=e=>{e.stopPropagation();s.selected=stop;s.gesture.start(e,b!,p=>{const r=ui.preview.getBoundingClientRect();stop.t=projectOnLine((p.clientX-r.left)/r.width,(p.clientY-r.top)/r.height,s.line,r.width,r.height);s.stops.sort((a,b)=>a.t-b.t);this.changed();});};b.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();this.openColor(stop,b!);}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();stop.t=unit(stop.t+(e.key==='ArrowLeft'?-.01:.01));s.stops.sort((a,b)=>a.t-b.t);this.changed();}};ui.preview.appendChild(b);ui.lineStops.set(stop,b);}b.hidden=!linear||stop.t<=.001||stop.t>=.999;b.style.left=`${(line.start.x+(line.end.x-line.start.x)*stop.t)*100}%`;b.style.top=`${(line.start.y+(line.end.y-line.start.y)*stop.t)*100}%`;b.style.setProperty('--color',rgba(stop.color));b.setAttribute('aria-pressed',String(stop===s.selected));}
 const c=(shape?s.point:s.selected).color,values:Record<string,string|number>={angle:s.angle,cx:s.cx,cy:s.cy,position:s.selected.t*100,alpha:c.a*100,radius:(s.point.radius??.6)*100,x:s.point.x*100,y:s.point.y*100,interp:s.interp,shape:s.shape,size:s.size};for(const [k,n]of ui.fields){if(document.activeElement!==n)n.value=String(typeof values[k]==='number'?Math.round((values[k] as number)*100)/100:values[k]);n.parentElement!.hidden=k==='angle'?this.mode!=='linear':['cx','cy','shape','size'].includes(k)?this.mode!=='radial':['radius','x','y'].includes(k)?!shape:['position','interp'].includes(k)?shape:false;}ui.color.value=colorFieldHex(c);if(document.activeElement!==ui.hex)ui.hex.value=colorFieldHex(c);ui.del.disabled=shape?s.points.length<=1:s.stops.length<=2;ui.css.value=this.toCSS();this.schedule();}
 private paintShape():void{const s=state(this),canvas=s.ui?.canvas,ctx=canvas?.getContext('2d');if(!ctx||!canvas)return;const rect=s.ui!.preview.getBoundingClientRect(),dpr=Math.min(3,window.devicePixelRatio||1),width=Math.max(1,Math.min(1600,Math.round((rect.width||360)*dpr))),height=Math.max(1,Math.min(1600,Math.round((rect.height||240)*dpr)));if(canvas.width!==width)canvas.width=width;if(canvas.height!==height)canvas.height=height;const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);for(const p of s.points){const r=Math.max(w,h)*(p.radius??.6),g=ctx.createRadialGradient(p.x*w,p.y*h,0,p.x*w,p.y*h,r);g.addColorStop(0,rgba(p.color));g.addColorStop(1,`rgba(${p.color.r},${p.color.g},${p.color.b},0)`);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);}}
}
