/** @module components/graphics/colors/GraphicsColorPicker */
import { Component, Css, Templates } from '../../../core/index.ts';
const html=Templates.Template.Html;
export namespace GraphicsColorPicker {
 export namespace Types{export type Theme='dark'|'light';}
 export namespace Interfaces{export interface RGB{r:number;g:number;b:number;}export interface HSL{h:number;s:number;l:number;}export interface Color{rgb:RGB;hsl:HSL;hex:string;alpha:number;}export interface ColorPickerOptions{value?:string;color?:string;alpha?:number;theme?:Types.Theme;}}
 export const clamp=(v:number,a=0,b=1):number=>Math.max(a,Math.min(b,Number.isFinite(v)?v:a));
 export function parseHexRgba(value:string):Interfaces.Color{let h=String(value||'#E40C88').trim().replace('#','');if(h.length===3||h.length===4)h=h.split('').map(x=>x+x).join('');if(!/^[0-9a-f]{6}([0-9a-f]{2})?$/i.test(h))h='E40C88';const rgb={r:parseInt(h.slice(0,2),16),g:parseInt(h.slice(2,4),16),b:parseInt(h.slice(4,6),16)};const alpha=h.length===8?parseInt(h.slice(6,8),16)/255:1;return{rgb,hsl:rgbToHsl(rgb),hex:rgbToHex(rgb),alpha};}
 export function rgbToHex(rgb:Interfaces.RGB):string{return`#${[rgb.r,rgb.g,rgb.b].map(v=>Math.round(clamp(v,0,255)).toString(16).padStart(2,'0')).join('').toUpperCase()}`;}
 export function rgbToHsl(rgb:Interfaces.RGB):Interfaces.HSL{const r=rgb.r/255,g=rgb.g/255,b=rgb.b/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,l=(max+min)/2;let h=0;if(d){if(max===r)h=((g-b)/d)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360;}const s=d===0?0:d/(1-Math.abs(2*l-1));return{h,s:s*100,l:l*100};}
 export function hslToRgb(hsl:Interfaces.HSL):Interfaces.RGB{const h=((hsl.h%360)+360)%360,s=clamp(hsl.s/100),l=clamp(hsl.l/100),c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2;let r=0,g=0,b=0;if(h<60){r=c;g=x}else if(h<120){r=x;g=c}else if(h<180){g=c;b=x}else if(h<240){g=x;b=c}else if(h<300){r=x;b=c}else{r=c;b=x}return{r:(r+m)*255,g:(g+m)*255,b:(b+m)*255};}
 interface State{bound:boolean;color:Interfaces.Color;}
 const states=new WeakMap<HTMLElement,State>();const state=(el:HTMLElement):State=>{let s=states.get(el);if(!s){s={bound:false,color:parseHexRgba(el.getAttribute('value')||el.getAttribute('color')||'#E40C88')};states.set(el,s);}return s;};
 export const Styles=new Css.Stylesheet([
  new Css.Rule('arianna-graphics-color-picker,.GraphicsColorPicker',{Background:'#202428',Border:'1px solid #111417',BorderRadius:'8px',BoxSizing:'border-box',Color:'#e6e9eb',Display:'block',FontFamily:'var(--arianna-font,system-ui,sans-serif)',Overflow:'hidden',Width:'330px'}),
  new Css.Rule('.GraphicsColorPicker-Header',{AlignItems:'center',Background:'linear-gradient(180deg,#383d42,#292d31)',BorderBottom:'1px solid #111417',Display:'flex',FontSize:'10px',FontWeight:'800',JustifyContent:'space-between',Padding:'8px 10px'}),
  new Css.Rule('.GraphicsColorPicker-Body',{Display:'grid',Gap:'9px',Padding:'10px'}),new Css.Rule('.GraphicsColorPicker-SV',{Background:'linear-gradient(to top,#000,transparent),linear-gradient(to right,#fff,transparent),hsl(var(--hue),100%,50%)',Border:'1px solid #0e1012',BorderRadius:'5px',Cursor:'crosshair',Height:'170px',Position:'relative'}),
  new Css.Rule('.GraphicsColorPicker-Cursor',{Border:'2px solid #fff',BorderRadius:'50%',BoxShadow:'0 0 0 1px #000',Height:'12px',Left:'0',PointerEvents:'none',Position:'absolute',Top:'0',Transform:'translate(-50%,-50%)',Width:'12px'}),
  new Css.Rule('.GraphicsColorPicker-Range',{AccentColor:'#e40c88',Cursor:'pointer',Margin:'0',Width:'100%'}),new Css.Rule('.GraphicsColorPicker-Fields',{Display:'grid',Gap:'5px',GridTemplateColumns:'1.4fr repeat(4,1fr)'}),
  new Css.Rule('.GraphicsColorPicker-Field',{Background:'#171b1e',Border:'1px solid #3a4045',BorderRadius:'3px',Color:'#e7eaec',Font:'9px ui-monospace,monospace',MinWidth:'0',Padding:'6px'}),new Css.Rule('.GraphicsColorPicker-Swatches',{Display:'grid',Gap:'4px',GridTemplateColumns:'repeat(8,1fr)'}),new Css.Rule('.GraphicsColorPicker-Swatch',{Appearance:'none',Border:'1px solid rgba(255,255,255,.25)',BorderRadius:'3px',Cursor:'pointer',Height:'24px'}),
  new Css.Rule('arianna-graphics-color-picker[theme="light"],.GraphicsColorPicker[theme="light"]',{Background:'#f4f5f6',BorderColor:'#b8bec3',Color:'#252b30'}),new Css.Rule('arianna-graphics-color-picker[theme="light"] .GraphicsColorPicker-Header',{Background:'linear-gradient(180deg,#fff,#e2e5e8)',BorderBottomColor:'#b8bec3'}),new Css.Rule('arianna-graphics-color-picker[theme="light"] .GraphicsColorPicker-Field',{Background:'#fff',BorderColor:'#c4c9ce',Color:'#30373d'})
 ]);
 @Component('arianna-graphics-color-picker',Styles,{Shadow:false,Attributes:['value','color','alpha','theme']})
 export class GraphicsColorPicker extends HTMLElement{
  public static readonly Styles=Styles;public template=html``;
  public onCreated():void{if(this.isConnected)this.onConnected();}public onConnected():void{this.classList.add('GraphicsColorPicker');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');const s=state(this);const raw=this.getAttribute('value')||this.getAttribute('color');if(raw)s.color=parseHexRgba(raw);if(this.hasAttribute('alpha'))s.color.alpha=clamp(Number(this.getAttribute('alpha')),0,1);this.render();}
  public onAttributeChanged(name:string):void{if(!this.isConnected)return;if(name==='value'||name==='color'){state(this).color=parseHexRgba(this.getAttribute(name)||'#E40C88');this.render();}else if(name==='alpha'){state(this).color.alpha=clamp(Number(this.getAttribute('alpha')),0,1);this.render();}}
  public get value():string{return state(this).color.hex;}public set value(v:string){this.setColor(v);}public get Color():Interfaces.Color{return structuredClone(state(this).color);}public getColor():Interfaces.Color{return this.Color;}
  public setColor(c:string|Partial<Interfaces.RGB>|Partial<Interfaces.HSL>|{hex?:string;alpha?:number}):this{const s=state(this);if(typeof c==='string')s.color=parseHexRgba(c);else if('hex'in c&&c.hex)s.color=parseHexRgba(c.hex);else if('r'in c||'g'in c||'b'in c){const rgb={r:Number((c as Partial<Interfaces.RGB>).r??s.color.rgb.r),g:Number((c as Partial<Interfaces.RGB>).g??s.color.rgb.g),b:Number((c as Partial<Interfaces.RGB>).b??s.color.rgb.b)};s.color={rgb,hsl:rgbToHsl(rgb),hex:rgbToHex(rgb),alpha:s.color.alpha};}else if('h'in c||'s'in c||'l'in c){const hsl={h:Number((c as Partial<Interfaces.HSL>).h??s.color.hsl.h),s:Number((c as Partial<Interfaces.HSL>).s??s.color.hsl.s),l:Number((c as Partial<Interfaces.HSL>).l??s.color.hsl.l)};const rgb=hslToRgb(hsl);s.color={rgb,hsl,hex:rgbToHex(rgb),alpha:s.color.alpha};}if(typeof c!=='string'&&'alpha'in c&&typeof c.alpha==='number')s.color.alpha=clamp(c.alpha);this.setAttribute('value',s.color.hex);this.render();this.emit();return this;}
  private render():void{const s=state(this),hsl=s.color.hsl;const val=Math.max(0,Math.min(100,hsl.l<=50?hsl.l*2:100-(hsl.l-50)*.45));const sat=Math.max(0,Math.min(100,hsl.s));this.style.setProperty('--hue',String(Math.round(hsl.h)));this.style.setProperty('--sat',String(sat));this.style.setProperty('--val',String(val));const root=document.createElement('section'),head=document.createElement('header');head.className='GraphicsColorPicker-Header';head.innerHTML='<span>Color</span>';const chip=document.createElement('span');chip.style.cssText=`width:42px;height:16px;border-radius:3px;border:1px solid rgba(255,255,255,.3);background:${s.color.hex}`;head.appendChild(chip);const body=document.createElement('div');body.className='GraphicsColorPicker-Body';const sv=document.createElement('div');sv.className='GraphicsColorPicker-SV';const cur=document.createElement('span');cur.className='GraphicsColorPicker-Cursor';cur.style.left=`${sat}%`;cur.style.top=`${100-val}%`;sv.appendChild(cur);const hue=document.createElement('input');hue.type='range';hue.min='0';hue.max='360';hue.value=String(Math.round(hsl.h));hue.className='GraphicsColorPicker-Range';hue.style.background='linear-gradient(90deg,#f00,#ff0,#0f0,#0ff,#00f,#f0f,#f00)';const alpha=document.createElement('input');alpha.type='range';alpha.min='0';alpha.max='100';alpha.value=String(Math.round(s.color.alpha*100));alpha.className='GraphicsColorPicker-Range';const fields=document.createElement('div');fields.className='GraphicsColorPicker-Fields';for(const [k,v] of [['HEX',s.color.hex],['R',Math.round(s.color.rgb.r)],['G',Math.round(s.color.rgb.g)],['B',Math.round(s.color.rgb.b)],['A',Math.round(s.color.alpha*100)]] as [string,string|number][]){const inp=document.createElement('input');inp.className='GraphicsColorPicker-Field';inp.value=String(v);inp.title=k;inp.dataset.field=k;fields.appendChild(inp);}const sw=document.createElement('div');sw.className='GraphicsColorPicker-Swatches';['#E40C88','#6954D8','#3489D8','#35B875','#F0C84B','#F28A42','#E0525B','#F4F5F6','#2B2F34','#8C6BD8','#43C7C2','#7FBF5A','#F08BC0','#9D4EDD','#3568D4','#111315'].forEach(c=>{const b=document.createElement('button');b.className='GraphicsColorPicker-Swatch';b.style.background=c;b.onclick=()=>this.setColor(c);sw.appendChild(b);});body.append(sv,hue,alpha,fields,sw);root.append(head,body);this.replaceChildren(root);
   sv.onpointerdown=e=>{const r=sv.getBoundingClientRect();const S=clamp((e.clientX-r.left)/r.width),V=clamp(1-(e.clientY-r.top)/r.height);const L=V*(1-S/2),den=Math.min(L,1-L);const sat2=den===0?0:(V-L)/den;this.setColor({h:hsl.h,s:sat2*100,l:L*100});};hue.oninput=()=>this.setColor({h:Number(hue.value),s:state(this).color.hsl.s,l:state(this).color.hsl.l});alpha.oninput=()=>this.setColor({hex:state(this).color.hex,alpha:Number(alpha.value)/100});fields.addEventListener('change',e=>{const inp=e.target as HTMLInputElement;if(inp.dataset.field==='HEX')this.setColor(inp.value);else{const c=state(this).color.rgb;this.setColor({r:inp.dataset.field==='R'?Number(inp.value):c.r,g:inp.dataset.field==='G'?Number(inp.value):c.g,b:inp.dataset.field==='B'?Number(inp.value):c.b});}});
  }
  private emit():void{this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{color:this.Color,value:this.value,source:this}}));}
 }
}
export const {parseHexRgba,rgbToHex,rgbToHsl,hslToRgb}=GraphicsColorPicker;export type RGB=GraphicsColorPicker.Interfaces.RGB;export type HSL=GraphicsColorPicker.Interfaces.HSL;export type Color=GraphicsColorPicker.Interfaces.Color;export type ColorPickerOptions=GraphicsColorPicker.Interfaces.ColorPickerOptions;export default GraphicsColorPicker.GraphicsColorPicker;
