/** Composite colour studio. Existing solid-colour API is preserved. */
import {Component,Templates} from '../../../core/index.ts';
import HSVColorPicker from './HSVColorPicker.ts';
import LinearGradientEditor from './LinearGradientEditor.ts';
import {PickerStyles,installPickerStyle,el,button} from './PickerUI.ts';
import type {PickerGeometry} from './ColorSpacePickerBase.ts';
import type {GradientMode} from './GradientPickerBase.ts';
export namespace GraphicsColorPicker {
 export namespace Types{export type Theme='dark'|'light';}
 export namespace Interfaces{export interface RGB{r:number;g:number;b:number;}export interface HSL{h:number;s:number;l:number;}export interface Color{rgb:RGB;hsl:HSL;hex:string;alpha:number;}export interface ColorPickerOptions{value?:string;color?:string;alpha?:number;theme?:Types.Theme;}}
 export const clamp=(v:number,a=0,b=1):number=>Math.max(a,Math.min(b,Number.isFinite(v)?v:a));
 export function parseHexRgba(value:string):Interfaces.Color{let h=String(value||'#E40C88').trim().replace('#','');if(h.length===3||h.length===4)h=h.split('').map(x=>x+x).join('');if(!/^[0-9a-f]{6}([0-9a-f]{2})?$/i.test(h))h='E40C88';const rgb={r:parseInt(h.slice(0,2),16),g:parseInt(h.slice(2,4),16),b:parseInt(h.slice(4,6),16)};const alpha=h.length===8?parseInt(h.slice(6,8),16)/255:1;return{rgb,hsl:rgbToHsl(rgb),hex:rgbToHex(rgb),alpha};}
 export function rgbToHex(rgb:Interfaces.RGB):string{return`#${[rgb.r,rgb.g,rgb.b].map(v=>Math.round(clamp(v,0,255)).toString(16).padStart(2,'0')).join('').toUpperCase()}`;}
 export function rgbToHsl(rgb:Interfaces.RGB):Interfaces.HSL{const r=rgb.r/255,g=rgb.g/255,b=rgb.b/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,l=(max+min)/2;let h=0;if(d){if(max===r)h=((g-b)/d)%6;else if(max===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360;}const s=d===0?0:d/(1-Math.abs(2*l-1));return{h,s:s*100,l:l*100};}
 export function hslToRgb(hsl:Interfaces.HSL):Interfaces.RGB{const h=((hsl.h%360)+360)%360,s=clamp(hsl.s/100),l=clamp(hsl.l/100),c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2;let r=0,g=0,b=0;if(h<60){r=c;g=x}else if(h<120){r=x;g=c}else if(h<180){g=c;b=x}else if(h<240){g=x;b=c}else if(h<300){r=x;b=c}else{r=c;b=x}return{r:(r+m)*255,g:(g+m)*255,b:(b+m)*255};}

 interface State{color:Interfaces.Color;solid?:HSVColorPicker;gradient?:LinearGradientEditor;body?:HTMLElement;tabs?:Map<string,HTMLButtonElement>;mode:'solid'|GradientMode;internal:boolean;}
 const states=new WeakMap<object,State>();const state=(o:object):State=>{let s=states.get(o);if(!s){s={color:parseHexRgba('#E40C88'),mode:'solid',internal:false};states.set(o,s);}return s;};
 export const Styles=PickerStyles;
 @Component('arianna-graphics-color-picker',Styles,{Shadow:false,Attributes:['value','color','alpha','theme','geometry'],Properties:['mode']})
 export class GraphicsColorPicker extends HTMLElement{
 private reflectAttribute(name:string,value:string):void{if(this.getAttribute(name)!==value)this.setAttribute(name,value);}
  public static readonly Styles=Styles;public template=Templates.Template.Html``;
  public get value():string{return this.Color.hex;}public set value(v:string){this.setColor(v);}
  public get Color():Interfaces.Color{return structuredClone(state(this).color);}public getColor():Interfaces.Color{return this.Color;}
  public get mode():'solid'|GradientMode{return state(this).mode;}public set mode(v:'solid'|GradientMode){if(!['solid','linear','radial','shape'].includes(v))return;state(this).mode=v;this.sync();}
  public get Solid():HSVColorPicker|undefined{return state(this).solid;}
  public get Gradient():LinearGradientEditor|undefined{return state(this).gradient;}
  public setColor(c:string|Partial<Interfaces.RGB>|Partial<Interfaces.HSL>|{hex?:string;alpha?:number}):this{const s=state(this);if(typeof c==='string')s.color=parseHexRgba(c);else if('hex'in c&&c.hex)s.color=parseHexRgba(c.hex);else if('r'in c||'g'in c||'b'in c){const rgb={...s.color.rgb,...c} as Interfaces.RGB;s.color={rgb,hsl:rgbToHsl(rgb),hex:rgbToHex(rgb),alpha:s.color.alpha};}else if('h'in c||'s'in c||'l'in c){const hsl={...s.color.hsl,...c} as Interfaces.HSL;const rgb=hslToRgb(hsl);s.color={rgb,hsl,hex:rgbToHex(rgb),alpha:s.color.alpha};}if(typeof c!=='string'&&'alpha'in c&&typeof c.alpha==='number')s.color.alpha=clamp(c.alpha);s.internal=true;try{this.reflectAttribute('value',s.color.hex);this.reflectAttribute('alpha',String(s.color.alpha));}finally{s.internal=false;}if(s.solid)s.solid.setColor({...s.color.rgb,a:s.color.alpha});else this.emit();return this;}
  public onCreated():void{if(this.isConnected)this.onConnected();}
  public onConnected():void{installPickerStyle(this);const s=state(this);if(!s.body){const raw=this.getAttribute('value')||this.getAttribute('color');if(raw)s.color=parseHexRgba(raw);if(this.hasAttribute('alpha'))s.color.alpha=clamp(Number(this.getAttribute('alpha')));const tabs=el('div','cp-tabs'),map=new Map<string,HTMLButtonElement>();tabs.setAttribute('role','tablist');for(const m of ['solid','linear','radial','shape'] as const){const b=button(m[0].toUpperCase()+m.slice(1),()=>this.mode=m);b.setAttribute('role','tab');tabs.appendChild(b);map.set(m,b);}const body=el('div','cp-panel');s.body=body;s.tabs=map;const solid=new HSVColorPicker();s.solid=solid;solid.geometry=(this.getAttribute('geometry') as PickerGeometry)||'ring';solid.setColor({...s.color.rgb,a:s.color.alpha});solid.addEventListener('arianna:change',e=>{e.stopPropagation();const c=solid.getColor();s.color={rgb:{r:c.r,g:c.g,b:c.b},hsl:rgbToHsl(c),hex:rgbToHex(c),alpha:c.a??1};this.emit();});body.appendChild(solid);this.replaceChildren(tabs,body);}this.sync();}
  public onAttributeChanged(n:string):void{const s=state(this);if(s.internal)return;if(n==='value'||n==='color')this.setColor(this.getAttribute(n)||'#E40C88');else if(n==='alpha')this.setColor({alpha:Number(this.getAttribute(n))});else if(n==='geometry'&&s.solid)s.solid.geometry=this.getAttribute(n) as PickerGeometry;else if(n==='theme')this.sync();}
  private sync():void{const s=state(this);if(!s.body)return;const theme=this.getAttribute('theme')||'dark';s.solid!.setAttribute('theme',theme);s.solid!.hidden=s.mode!=='solid';if(s.mode!=='solid'){if(!s.gradient){const g=new LinearGradientEditor();s.gradient=g;g.classList.add('cp-gradient-embedded');g.addEventListener('arianna:change',e=>{e.stopPropagation();this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{...(e as CustomEvent).detail,source:this}}));});s.body.appendChild(g);}s.gradient.mode=s.mode;s.gradient.setAttribute('theme',theme);}if(s.gradient)s.gradient.hidden=s.mode==='solid';for(const [m,b]of s.tabs!)b.setAttribute('aria-selected',String(m===s.mode));}
  private emit():void{const s=state(this);s.internal=true;try{this.reflectAttribute('value',s.color.hex);this.reflectAttribute('alpha',String(s.color.alpha));}finally{s.internal=false;}this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{color:this.Color,value:this.value,source:this}}));}
 }
}
export const {parseHexRgba,rgbToHex,rgbToHsl,hslToRgb}=GraphicsColorPicker;export type RGB=GraphicsColorPicker.Interfaces.RGB;export type HSL=GraphicsColorPicker.Interfaces.HSL;export type Color=GraphicsColorPicker.Interfaces.Color;export type ColorPickerOptions=GraphicsColorPicker.Interfaces.ColorPickerOptions;export default GraphicsColorPicker.GraphicsColorPicker;
