/** @module components/graphics/colors/LinearGradientEditor */
import { Component, Css, Templates } from '../../../core/index.ts';
import { DEFAULT_STOPS, sortStops, stopsToCss, colorFieldHex, sampleAt, clamp01, type GradientStop } from './GradientEditor.ts';
const html=Templates.Template.Html;
export namespace LinearGradientEditor {
 export namespace Types{export type GradientInterp='srgb'|'oklab'|'oklch'|'hsl';}
 export namespace Interfaces{export interface LinearGradientEditorOptions{stops?:GradientStop[];angle?:number;interpolation?:Types.GradientInterp;theme?:'dark'|'light';}}
 interface State{stops:GradientStop[];selected:number;}const States=new WeakMap<HTMLElement,State>();const S=(e:HTMLElement):State=>{let s=States.get(e);if(!s){s={stops:DEFAULT_STOPS(),selected:0};States.set(e,s);}return s;};
 const interpLabel=(v:Types.GradientInterp)=>v==='srgb'?'srgb':v;
 export const Styles=new Css.Stylesheet([
  new Css.Rule('arianna-linear-gradient-editor,.LinearGradientEditor',{Background:'var(--arianna-bg,#171a1d)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'12px',BoxSizing:'border-box',Color:'var(--arianna-text,#eef1f4)',Display:'block',FontFamily:'-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',Overflow:'hidden',Width:'470px',MaxWidth:'100%'}),
  new Css.Rule('.gs-head',{AlignItems:'center',Background:'var(--arianna-bg-2,#202428)',BorderBottom:'1px solid var(--arianna-border,#3a4046)',Display:'flex',Gap:'10px',Padding:'11px 13px'}),new Css.Rule('.gs-head strong',{Flex:'1',FontSize:'13px'}),new Css.Rule('.gs-badge',{Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'999px',Color:'var(--arianna-muted,#9aa2aa)',Font:'800 9px ui-monospace,monospace',Padding:'3px 8px',TextTransform:'uppercase'}),
  new Css.Rule('.gs-body',{Display:'grid',Gap:'11px',Padding:'12px'}),new Css.Rule('.gs-preview',{Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'10px',Height:'170px'}),new Css.Rule('.gs-control-row',{AlignItems:'center',Display:'grid',Gap:'12px',GridTemplateColumns:'112px 1fr'}),
  new Css.Rule('.gs-dial',{Background:'radial-gradient(circle,var(--arianna-bg,#171a1d) 0 52%,transparent 53%),conic-gradient(from 0deg,#31363b,#555b61,#31363b)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'50%',Cursor:'crosshair',Height:'106px',Position:'relative',TouchAction:'none',Width:'106px'}),new Css.Rule('.gs-dial-line',{Background:'var(--arianna-primary,#e40c88)',Height:'2px',Left:'50%',Position:'absolute',Top:'50%',Transform:'rotate(var(--gs-angle))',TransformOrigin:'0 50%',Width:'42px'}),new Css.Rule('.gs-dial-knob',{Background:'var(--arianna-primary,#e40c88)',Border:'2px solid #fff',BorderRadius:'50%',Height:'10px',Left:'calc(50% + cos(var(--gs-angle))*42px)',Position:'absolute',Top:'50%',Transform:'translate(-50%,-50%)',Width:'10px'}),
  new Css.Rule('.gs-direction-grid',{Display:'grid',Gap:'5px',GridTemplateColumns:'repeat(3,34px)'}),new Css.Rule('.gs-dir,.gs-button',{Appearance:'none',Background:'var(--arianna-bg-2,#202428)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'7px',Color:'var(--arianna-text,#eef1f4)',Cursor:'pointer',Font:'700 11px system-ui',MinHeight:'31px'}),new Css.Rule('.gs-dir:hover,.gs-button:hover',{BorderColor:'var(--arianna-primary,#e40c88)'}),new Css.Rule('.gs-right',{Display:'grid',Gap:'8px'}),new Css.Rule('.gs-selects',{Display:'grid',Gap:'6px',GridTemplateColumns:'1fr 1fr'}),new Css.Rule('.gs-input',{Background:'var(--arianna-bg,#171a1d)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'7px',BoxSizing:'border-box',Color:'var(--arianna-text,#eef1f4)',Font:'10px system-ui',MinWidth:'0',Padding:'7px'}),
  new Css.Rule('.gs-ramp-wrap',{PaddingBottom:'18px'}),new Css.Rule('.gs-ramp',{Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'7px',Cursor:'copy',Height:'32px',Position:'relative'}),new Css.Rule('.gs-stop',{Appearance:'none',Background:'var(--stop-color)',Border:'2px solid #fff',BorderRadius:'3px',BoxShadow:'0 0 0 1px #000',Cursor:'ew-resize',Height:'15px',Left:'calc(var(--stop-pos)*1%)',Padding:'0',Position:'absolute',Top:'27px',Transform:'translateX(-50%) rotate(45deg)',Width:'15px'}),new Css.Rule('.gs-stop[data-selected="true"]',{BoxShadow:'0 0 0 1px #000,0 0 0 4px var(--arianna-primary,#e40c88)'}),
  new Css.Rule('.gs-stop-edit',{AlignItems:'center',Display:'grid',Gap:'7px',GridTemplateColumns:'42px 1fr 82px 82px auto'}),new Css.Rule('.gs-hint',{Color:'var(--arianna-muted,#9aa2aa)',FontSize:'9px'}),
  new Css.Rule('.LinearGradientEditor[theme="light"]',{Background:'#f5f6f7',BorderColor:'#bcc2c7',Color:'#25292d'}),new Css.Rule('.LinearGradientEditor[theme="light"] .gs-head,.LinearGradientEditor[theme="light"] .gs-dir,.LinearGradientEditor[theme="light"] .gs-button',{Background:'#fff'}),new Css.Rule('.LinearGradientEditor[theme="light"] .gs-input',{Background:'#fff',Color:'#25292d'})
 ]);
 @Component('arianna-linear-gradient-editor',Styles,{Shadow:false,Attributes:['theme','angle','interp','interpolation'],Properties:['stops']})
 export class LinearGradientEditor extends HTMLElement{
  public static readonly Styles=Styles;public template=html``;public onCreated():void{if(this.isConnected)this.onConnected();}public onConnected():void{this.classList.add('LinearGradientEditor');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');if(!this.hasAttribute('angle'))this.setAttribute('angle','90');this.Render();}public onAttributeChanged(n:string):void{if(this.isConnected&&['angle','interp','interpolation','theme'].includes(n))this.Render();}
  public get stops():GradientStop[]{return structuredClone(S(this).stops);}public set stops(v:GradientStop[]){S(this).stops=Array.isArray(v)&&v.length?sortStops(structuredClone(v)):DEFAULT_STOPS();S(this).selected=Math.min(S(this).selected,S(this).stops.length-1);this.Render();}public getAngle():number{const n=Number(this.getAttribute('angle')??90);return Number.isFinite(n)?((n%360)+360)%360:90;}public setAngle(v:number):this{this.setAttribute('angle',String(((v%360)+360)%360));this.Render();this.Emit();return this;}public getInterp():Types.GradientInterp{return((this.getAttribute('interp')||this.getAttribute('interpolation'))as Types.GradientInterp)||'oklab';}public setInterp(v:Types.GradientInterp):this{this.setAttribute('interp',v);this.Render();this.Emit();return this;}public setStops(v:GradientStop[]):this{this.stops=v;this.Emit();return this;}public getStops():GradientStop[]{return this.stops;}public toCSS():string{const i=this.getInterp();return`linear-gradient(${this.getAngle()}deg${i==='srgb'?'':` in ${interpLabel(i)}`}, ${stopsToCss(S(this).stops)})`;}
  private Emit():void{this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{type:'linear',stops:this.getStops(),angle:this.getAngle(),interpolation:this.getInterp(),css:this.toCSS(),source:this}}));}
  private addStop(t:number):void{const s=S(this),stop:GradientStop={t:clamp01(t),color:sampleAt(s.stops,t)};s.stops=sortStops([...s.stops,stop]);s.selected=s.stops.indexOf(stop);this.Render();this.Emit();}
  private Render():void{const s=S(this),root=document.createElement('section'),head=document.createElement('header');head.className='gs-head';head.innerHTML='<strong>Gradient Studio</strong><span class="gs-badge">Linear</span>';const body=document.createElement('div');body.className='gs-body';const preview=document.createElement('div');preview.className='gs-preview';preview.style.background=this.toCSS();const control=document.createElement('div');control.className='gs-control-row';const dial=document.createElement('div');dial.className='gs-dial';dial.style.setProperty('--gs-angle',`${this.getAngle()-90}deg`);const line=document.createElement('span');line.className='gs-dial-line';const knob=document.createElement('span');knob.className='gs-dial-knob';dial.append(line,knob);const setDial=(e:PointerEvent)=>{const r=dial.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;this.setAngle(Math.atan2(e.clientY-cy,e.clientX-cx)*180/Math.PI+90);};dial.onpointerdown=e=>{e.preventDefault();setDial(e);const m=(x:PointerEvent)=>setDial(x),u=()=>{window.removeEventListener('pointermove',m,true);window.removeEventListener('pointerup',u,true)};window.addEventListener('pointermove',m,true);window.addEventListener('pointerup',u,true)};const right=document.createElement('div');right.className='gs-right';const dirs=document.createElement('div');dirs.className='gs-direction-grid';const presets:[string,number][]=[['↖',315],['↑',0],['↗',45],['←',270],['•',90],['→',90],['↙',225],['↓',180],['↘',135]];for(const[label,a]of presets){const b=document.createElement('button');b.className='gs-dir';b.textContent=label;b.title=`${a}°`;b.onclick=()=>this.setAngle(a);dirs.appendChild(b);}const selects=document.createElement('div');selects.className='gs-selects';const angle=document.createElement('input');angle.className='gs-input';angle.type='number';angle.min='0';angle.max='360';angle.value=String(Math.round(this.getAngle()));angle.onchange=()=>this.setAngle(Number(angle.value));const interp=document.createElement('select');interp.className='gs-input';interp.innerHTML='<option value="srgb">sRGB</option><option value="oklab">OKLab</option><option value="oklch">OKLCH</option><option value="hsl">HSL</option>';interp.value=this.getInterp();interp.onchange=()=>this.setInterp(interp.value as Types.GradientInterp);selects.append(angle,interp);right.append(dirs,selects);control.append(dial,right);
   const wrap=document.createElement('div');wrap.className='gs-ramp-wrap';const ramp=document.createElement('div');ramp.className='gs-ramp';ramp.style.background=`linear-gradient(90deg,${stopsToCss(s.stops)})`;ramp.onclick=e=>{if((e.target as Element).closest('.gs-stop'))return;const r=ramp.getBoundingClientRect();this.addStop((e.clientX-r.left)/r.width);};s.stops.forEach((stop,i)=>{const b=document.createElement('button');b.className='gs-stop';b.style.setProperty('--stop-pos',String(stop.t*100));b.style.setProperty('--stop-color',colorFieldHex(stop.color));b.dataset.selected=String(i===s.selected);b.onclick=e=>{e.stopPropagation();s.selected=i;this.Render();};b.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const move=(ev:PointerEvent)=>{const r=ramp.getBoundingClientRect();stop.t=clamp01((ev.clientX-r.left)/r.width);s.stops=sortStops(s.stops);s.selected=s.stops.indexOf(stop);this.Render();this.Emit();},up=()=>{window.removeEventListener('pointermove',move,true);window.removeEventListener('pointerup',up,true)};window.addEventListener('pointermove',move,true);window.addEventListener('pointerup',up,true);};ramp.appendChild(b)});wrap.appendChild(ramp);
   const selected=s.stops[s.selected]??s.stops[0],edit=document.createElement('div');edit.className='gs-stop-edit';const col=document.createElement('input');col.type='color';col.value=colorFieldHex(selected.color);col.oninput=()=>{const x=col.value.slice(1);selected.color={...selected.color,r:parseInt(x.slice(0,2),16),g:parseInt(x.slice(2,4),16),b:parseInt(x.slice(4,6),16)};this.Render();this.Emit();};const pos=document.createElement('input');pos.className='gs-input';pos.type='number';pos.min='0';pos.max='100';pos.value=String(Math.round(selected.t*100));pos.onchange=()=>{selected.t=clamp01(Number(pos.value)/100);s.stops=sortStops(s.stops);s.selected=s.stops.indexOf(selected);this.Render();this.Emit();};const alpha=document.createElement('input');alpha.className='gs-input';alpha.type='number';alpha.min='0';alpha.max='100';alpha.value=String(Math.round(selected.color.a*100));alpha.onchange=()=>{selected.color.a=clamp01(Number(alpha.value)/100);this.Render();this.Emit();};const del=document.createElement('button');del.className='gs-button';del.textContent='Delete';del.disabled=s.stops.length<=2;del.onclick=()=>{if(s.stops.length<=2)return;s.stops.splice(s.selected,1);s.selected=Math.max(0,Math.min(s.selected,s.stops.length-1));this.Render();this.Emit();};const lab=document.createElement('span');lab.className='gs-hint';lab.textContent='Stop';edit.append(lab,col,pos,alpha,del);const hint=document.createElement('div');hint.className='gs-hint';hint.textContent='Click the gradient ramp to add a stop · drag stops to move · use the dial or direction buttons.';body.append(preview,control,wrap,edit,hint);root.append(head,body);this.replaceChildren(root);}
 }
}
export type GradientInterp=LinearGradientEditor.Types.GradientInterp;export type LinearGradientEditorOptions=LinearGradientEditor.Interfaces.LinearGradientEditorOptions;export default LinearGradientEditor.LinearGradientEditor;
