import type { PickerConfig } from './ColorSpacePickerBase.ts';
export const PickerConfigs:Record<string,PickerConfig>={
'rgb':{space:'rgb',title:'RGB Color Picker',geometry:'plane',channels:[{key:'r',label:'R',min:0,max:255,step:1,decimals:0},{key:'g',label:'G',min:0,max:255,step:1,decimals:0},{key:'b',label:'B',min:0,max:255,step:1,decimals:0}],plane:['r','g']},
'xyz':{space:'xyz',title:'CIE 1931 XYZ Color Picker',geometry:'plane',channels:[{key:'X',label:'X',min:0,max:95.047,step:.01,decimals:2},{key:'Y',label:'Y',min:0,max:100,step:.01,decimals:2},{key:'Z',label:'Z',min:0,max:108.883,step:.01,decimals:2}],plane:['X','Y']},
'cmyk':{space:'cmyk',title:'CMYK Color Picker',geometry:'plane',channels:[{key:'c',label:'C',min:0,max:100,step:.1,unit:'%',decimals:1},{key:'m',label:'M',min:0,max:100,step:.1,unit:'%',decimals:1},{key:'y',label:'Y',min:0,max:100,step:.1,unit:'%',decimals:1},{key:'k',label:'K',min:0,max:100,step:.1,unit:'%',decimals:1}],plane:['c','m']},
'lab':{space:'lab',title:'CIELAB Color Picker',geometry:'plane',channels:[{key:'L',label:'L*',min:0,max:100,step:.1,decimals:1},{key:'a',label:'a*',min:-128,max:127,step:.1,decimals:1},{key:'b',label:'b*',min:-128,max:127,step:.1,decimals:1}],plane:['a','b']},
'okhsl':{space:'okhsl',title:'OKHSL Color Picker',geometry:'wheel',channels:[{key:'h',label:'H',min:0,max:360,step:.1,unit:'°',decimals:1},{key:'s',label:'S',min:0,max:100,step:.1,unit:'%',decimals:1},{key:'l',label:'L',min:0,max:100,step:.1,unit:'%',decimals:1}],hue:'h',saturation:'s',lightness:'l'},
'okhsv':{space:'okhsv',title:'OKHSV Color Picker',geometry:'square',channels:[{key:'h',label:'H',min:0,max:360,step:.1,unit:'°',decimals:1},{key:'s',label:'S',min:0,max:100,step:.1,unit:'%',decimals:1},{key:'v',label:'V',min:0,max:100,step:.1,unit:'%',decimals:1}],hue:'h',saturation:'s',value:'v'},
'hsv':{space:'hsv',title:'HSV Color Picker',geometry:'square',channels:[{key:'h',label:'H',min:0,max:360,step:.1,unit:'°',decimals:1},{key:'s',label:'S',min:0,max:100,step:.1,unit:'%',decimals:1},{key:'v',label:'V',min:0,max:100,step:.1,unit:'%',decimals:1}],hue:'h',saturation:'s',value:'v'},
'hsl':{space:'hsl',title:'HSL Color Picker',geometry:'wheel',channels:[{key:'h',label:'H',min:0,max:360,step:.1,unit:'°',decimals:1},{key:'s',label:'S',min:0,max:100,step:.1,unit:'%',decimals:1},{key:'l',label:'L',min:0,max:100,step:.1,unit:'%',decimals:1}],hue:'h',saturation:'s',lightness:'l'},
'uvw':{space:'uvw',title:'CIE UVW Color Picker',geometry:'plane',channels:[{key:'U',label:'U*',min:-120,max:180,step:.1,decimals:1},{key:'V',label:'V*',min:-150,max:120,step:.1,decimals:1},{key:'W',label:'W*',min:-17,max:83,step:.1,decimals:1}],plane:['U','V']},
'luv':{space:'luv',title:'CIE LUV Color Picker',geometry:'plane',channels:[{key:'L',label:'L*',min:0,max:100,step:.1,decimals:1},{key:'u',label:'u*',min:-134,max:220,step:.1,decimals:1},{key:'v',label:'v*',min:-140,max:122,step:.1,decimals:1}],plane:['u','v']}
};
