/** @module components/graphics/colors/RadialGradientEditor */
import { Component, Css, Templates } from '../../../core/index.ts';
import { DEFAULT_STOPS, sortStops, stopsToCss, colorFieldHex, sampleAt, clamp01, type GradientStop } from './GradientEditor.ts';
const html=Templates.Template.Html;
export namespace RadialGradientEditor {
 export namespace Types{export type RadialShape='circle'|'ellipse';export type RadialSize='closest-side'|'farthest-side'|'closest-corner'|'farthest-corner';export type GradientInterp='srgb'|'oklab'|'oklch'|'hsl';}
 export namespace Interfaces{export interface RadialGradientEditorOptions{stops?:GradientStop[];shape?:Types.RadialShape;size?:Types.RadialSize;cx?:number;cy?:number;interpolation?:Types.GradientInterp;theme?:'dark'|'light';}}
 interface State{stops:GradientStop[];selected:number;}const States=new WeakMap<HTMLElement,State>();const S=(e:HTMLElement):State=>{let s=States.get(e);if(!s){s={stops:DEFAULT_STOPS(),selected:0};States.set(e,s);}return s;};const pct=(n:number)=>Math.max(0,Math.min(100,Number.isFinite(n)?n:50));
 export const Styles=new Css.Stylesheet([
  new Css.Rule('arianna-radial-gradient-editor,.RadialGradientEditor',{Background:'var(--arianna-bg,#171a1d)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'12px',BoxSizing:'border-box',Color:'var(--arianna-text,#eef1f4)',Display:'block',FontFamily:'-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',Overflow:'hidden',Width:'470px',MaxWidth:'100%'}),
  new Css.Rule('.gs-head',{AlignItems:'center',Background:'var(--arianna-bg-2,#202428)',BorderBottom:'1px solid var(--arianna-border,#3a4046)',Display:'flex',Gap:'10px',Padding:'11px 13px'}),new Css.Rule('.gs-head strong',{Flex:'1',FontSize:'13px'}),new Css.Rule('.gs-badge',{Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'999px',Color:'var(--arianna-muted,#9aa2aa)',Font:'800 9px ui-monospace,monospace',Padding:'3px 8px',TextTransform:'uppercase'}),
  new Css.Rule('.gs-body',{Display:'grid',Gap:'11px',Padding:'12px'}),new Css.Rule('.gs-preview',{Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'10px',Height:'170px',Position:'relative'}),new Css.Rule('.gs-center-dot',{Background:'var(--arianna-primary,#e40c88)',Border:'2px solid #fff',BorderRadius:'50%',BoxShadow:'0 0 0 1px #000',Height:'12px',Left:'calc(var(--cx)*1%)',Position:'absolute',Top:'calc(var(--cy)*1%)',Transform:'translate(-50%,-50%)',Width:'12px'}),
  new Css.Rule('.gs-control-row',{AlignItems:'center',Display:'grid',Gap:'12px',GridTemplateColumns:'112px 1fr'}),new Css.Rule('.gs-center-control',{Background:'radial-gradient(circle at center,var(--arianna-bg,#171a1d) 0 56%,var(--arianna-bg-2,#202428) 57% 100%)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'50%',Cursor:'crosshair',Height:'106px',Position:'relative',TouchAction:'none',Width:'106px'}),new Css.Rule('.gs-center-control::before,.gs-center-control::after',{Background:'var(--arianna-border,#3a4046)',Content:'""',Position:'absolute'}),new Css.Rule('.gs-center-control::before',{Height:'1px',Left:'10%',Top:'50%',Width:'80%'}),new Css.Rule('.gs-center-control::after',{Height:'80%',Left:'50%',Top:'10%',Width:'1px'}),new Css.Rule('.gs-center-knob',{Background:'var(--arianna-primary,#e40c88)',Border:'2px solid #fff',BorderRadius:'50%',Height:'11px',Left:'calc(var(--cx)*1%)',Position:'absolute',Top:'calc(var(--cy)*1%)',Transform:'translate(-50%,-50%)',Width:'11px'}),
  new Css.Rule('.gs-direction-grid',{Display:'grid',Gap:'5px',GridTemplateColumns:'repeat(3,34px)'}),new Css.Rule('.gs-dir,.gs-button',{Appearance:'none',Background:'var(--arianna-bg-2,#202428)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'7px',Color:'var(--arianna-text,#eef1f4)',Cursor:'pointer',Font:'700 11px system-ui',MinHeight:'31px'}),new Css.Rule('.gs-dir:hover,.gs-button:hover',{BorderColor:'var(--arianna-primary,#e40c88)'}),new Css.Rule('.gs-right',{Display:'grid',Gap:'8px'}),new Css.Rule('.gs-selects',{Display:'grid',Gap:'6px',GridTemplateColumns:'repeat(3,1fr)'}),new Css.Rule('.gs-input',{Background:'var(--arianna-bg,#171a1d)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'7px',BoxSizing:'border-box',Color:'var(--arianna-text,#eef1f4)',Font:'10px system-ui',MinWidth:'0',Padding:'7px'}),
  new Css.Rule('.gs-ramp-wrap',{PaddingBottom:'18px'}),new Css.Rule('.gs-ramp',{Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'7px',Cursor:'copy',Height:'32px',Position:'relative'}),new Css.Rule('.gs-stop',{Appearance:'none',Background:'var(--stop-color)',Border:'2px solid #fff',BorderRadius:'3px',BoxShadow:'0 0 0 1px #000',Cursor:'ew-resize',Height:'15px',Left:'calc(var(--stop-pos)*1%)',Padding:'0',Position:'absolute',Top:'27px',Transform:'translateX(-50%) rotate(45deg)',Width:'15px'}),new Css.Rule('.gs-stop[data-selected="true"]',{BoxShadow:'0 0 0 1px #000,0 0 0 4px var(--arianna-primary,#e40c88)'}),
  new Css.Rule('.gs-stop-edit',{AlignItems:'center',Display:'grid',Gap:'7px',GridTemplateColumns:'42px 1fr 82px 82px auto'}),new Css.Rule('.gs-hint',{Color:'var(--arianna-muted,#9aa2aa)',FontSize:'9px'}),new Css.Rule('.RadialGradientEditor[theme="light"]',{Background:'#f5f6f7',BorderColor:'#bcc2c7',Color:'#25292d'}),new Css.Rule('.RadialGradientEditor[theme="light"] .gs-head,.RadialGradientEditor[theme="light"] .gs-dir,.RadialGradientEditor[theme="light"] .gs-button',{Background:'#fff'}),new Css.Rule('.RadialGradientEditor[theme="light"] .gs-input',{Background:'#fff',Color:'#25292d'})
 ]);
 @Component('arianna-radial-gradient-editor',Styles,{Shadow:false,Attributes:['theme','shape','size','cx','cy','interp','interpolation'],Properties:['stops']})
 export class RadialGradientEditor extends HTMLElement{
  public static readonly Styles=Styles;public template=html``;public onCreated():void{if(this.isConnected)this.onConnected();}public onConnected():void{this.classList.add('RadialGradientEditor');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');if(!this.hasAttribute('shape'))this.setAttribute('shape','ellipse');if(!this.hasAttribute('size'))this.setAttribute('size','farthest-corner');if(!this.hasAttribute('cx'))this.setAttribute('cx','50');if(!this.hasAttribute('cy'))this.setAttribute('cy','50');this.Render();}public onAttributeChanged(n:string):void{if(this.isConnected&&['shape','size','cx','cy','interp','interpolation','theme'].includes(n))this.Render();}
  public get stops():GradientStop[]{return structuredClone(S(this).stops);}public set stops(v:GradientStop[]){S(this).stops=Array.isArray(v)&&v.length?sortStops(structuredClone(v)):DEFAULT_STOPS();S(this).selected=Math.min(S(this).selected,S(this).stops.length-1);this.Render();}public setShape(v:Types.RadialShape):this{this.setAttribute('shape',v);this.Render();this.Fire();return this;}public setSize(v:Types.RadialSize):this{this.setAttribute('size',v);this.Render();this.Fire();return this;}public setCenter(cx:number,cy:number):this{this.setAttribute('cx',String(pct(cx)));this.setAttribute('cy',String(pct(cy)));this.Render();this.Fire();return this;}public setInterp(v:Types.GradientInterp):this{this.setAttribute('interp',v);this.Render();this.Fire();return this;}public getShape():Types.RadialShape{return(this.getAttribute('shape')as Types.RadialShape)||'ellipse';}public getSize():Types.RadialSize{return(this.getAttribute('size')as Types.RadialSize)||'farthest-corner';}public getCenter(){return{cx:pct(Number(this.getAttribute('cx')??50)),cy:pct(Number(this.getAttribute('cy')??50))};}public getInterp():Types.GradientInterp{return((this.getAttribute('interp')||this.getAttribute('interpolation'))as Types.GradientInterp)||'oklab';}public setStops(v:GradientStop[]):this{this.stops=v;this.Fire();return this;}public getStops():GradientStop[]{return this.stops;}public toCSS():string{const c=this.getCenter(),i=this.getInterp();return`radial-gradient(${this.getShape()} ${this.getSize()} at ${c.cx}% ${c.cy}%${i==='srgb'?'':` in ${i}`}, ${stopsToCss(S(this).stops)})`;}
  private Fire():void{this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{type:'radial',stops:this.getStops(),shape:this.getShape(),size:this.getSize(),center:this.getCenter(),interpolation:this.getInterp(),css:this.toCSS(),source:this}}));}
  private addStop(t:number):void{const s=S(this),stop:GradientStop={t:clamp01(t),color:sampleAt(s.stops,t)};s.stops=sortStops([...s.stops,stop]);s.selected=s.stops.indexOf(stop);this.Render();this.Fire();}
  private Render():void{const s=S(this),c=this.getCenter(),root=document.createElement('section'),head=document.createElement('header');head.className='gs-head';head.innerHTML='<strong>Gradient Studio</strong><span class="gs-badge">Radial</span>';const body=document.createElement('div');body.className='gs-body';const preview=document.createElement('div');preview.className='gs-preview';preview.style.background=this.toCSS();preview.style.setProperty('--cx',String(c.cx));preview.style.setProperty('--cy',String(c.cy));const pd=document.createElement('span');pd.className='gs-center-dot';preview.appendChild(pd);
   const control=document.createElement('div');control.className='gs-control-row';const center=document.createElement('div');center.className='gs-center-control';center.style.setProperty('--cx',String(c.cx));center.style.setProperty('--cy',String(c.cy));const knob=document.createElement('span');knob.className='gs-center-knob';center.appendChild(knob);const set=(e:PointerEvent)=>{const r=center.getBoundingClientRect();this.setCenter((e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100)};center.onpointerdown=e=>{e.preventDefault();set(e);const m=(x:PointerEvent)=>set(x),u=()=>{window.removeEventListener('pointermove',m,true);window.removeEventListener('pointerup',u,true)};window.addEventListener('pointermove',m,true);window.addEventListener('pointerup',u,true)};const right=document.createElement('div');right.className='gs-right';const dirs=document.createElement('div');dirs.className='gs-direction-grid';const preset:[string,number,number][]=[['↖',15,15],['↑',50,15],['↗',85,15],['←',15,50],['•',50,50],['→',85,50],['↙',15,85],['↓',50,85],['↘',85,85]];for(const[l,x,y]of preset){const b=document.createElement('button');b.className='gs-dir';b.textContent=l;b.onclick=()=>this.setCenter(x,y);dirs.appendChild(b)}const selects=document.createElement('div');selects.className='gs-selects';const shape=document.createElement('select');shape.className='gs-input';shape.innerHTML='<option value="ellipse">Ellipse</option><option value="circle">Circle</option>';shape.value=this.getShape();shape.onchange=()=>this.setShape(shape.value as Types.RadialShape);const size=document.createElement('select');size.className='gs-input';size.innerHTML='<option value="farthest-corner">Farthest corner</option><option value="closest-corner">Closest corner</option><option value="farthest-side">Farthest side</option><option value="closest-side">Closest side</option>';size.value=this.getSize();size.onchange=()=>this.setSize(size.value as Types.RadialSize);const interp=document.createElement('select');interp.className='gs-input';interp.innerHTML='<option value="srgb">sRGB</option><option value="oklab">OKLab</option><option value="oklch">OKLCH</option><option value="hsl">HSL</option>';interp.value=this.getInterp();interp.onchange=()=>this.setInterp(interp.value as Types.GradientInterp);selects.append(shape,size,interp);right.append(dirs,selects);control.append(center,right);
   const wrap=document.createElement('div');wrap.className='gs-ramp-wrap';const ramp=document.createElement('div');ramp.className='gs-ramp';ramp.style.background=`linear-gradient(90deg,${stopsToCss(s.stops)})`;ramp.onclick=e=>{if((e.target as Element).closest('.gs-stop'))return;const r=ramp.getBoundingClientRect();this.addStop((e.clientX-r.left)/r.width)};s.stops.forEach((stop,i)=>{const b=document.createElement('button');b.className='gs-stop';b.style.setProperty('--stop-pos',String(stop.t*100));b.style.setProperty('--stop-color',colorFieldHex(stop.color));b.dataset.selected=String(i===s.selected);b.onclick=e=>{e.stopPropagation();s.selected=i;this.Render()};b.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const m=(ev:PointerEvent)=>{const r=ramp.getBoundingClientRect();stop.t=clamp01((ev.clientX-r.left)/r.width);s.stops=sortStops(s.stops);s.selected=s.stops.indexOf(stop);this.Render();this.Fire()},u=()=>{window.removeEventListener('pointermove',m,true);window.removeEventListener('pointerup',u,true)};window.addEventListener('pointermove',m,true);window.addEventListener('pointerup',u,true)};ramp.appendChild(b)});wrap.appendChild(ramp);
   const p=s.stops[s.selected]??s.stops[0],edit=document.createElement('div');edit.className='gs-stop-edit';const lab=document.createElement('span');lab.className='gs-hint';lab.textContent='Stop';const col=document.createElement('input');col.type='color';col.value=colorFieldHex(p.color);col.oninput=()=>{const x=col.value.slice(1);p.color={...p.color,r:parseInt(x.slice(0,2),16),g:parseInt(x.slice(2,4),16),b:parseInt(x.slice(4,6),16)};this.Render();this.Fire()};const pos=document.createElement('input');pos.className='gs-input';pos.type='number';pos.min='0';pos.max='100';pos.value=String(Math.round(p.t*100));pos.onchange=()=>{p.t=clamp01(Number(pos.value)/100);s.stops=sortStops(s.stops);s.selected=s.stops.indexOf(p);this.Render();this.Fire()};const alpha=document.createElement('input');alpha.className='gs-input';alpha.type='number';alpha.min='0';alpha.max='100';alpha.value=String(Math.round(p.color.a*100));alpha.onchange=()=>{p.color.a=clamp01(Number(alpha.value)/100);this.Render();this.Fire()};const del=document.createElement('button');del.className='gs-button';del.textContent='Delete';del.disabled=s.stops.length<=2;del.onclick=()=>{if(s.stops.length<=2)return;s.stops.splice(s.selected,1);s.selected=Math.max(0,Math.min(s.selected,s.stops.length-1));this.Render();this.Fire()};edit.append(lab,col,pos,alpha,del);const hint=document.createElement('div');hint.className='gs-hint';hint.textContent='Drag the center in the circle or choose a direction preset · click the ramp to add stops.';body.append(preview,control,wrap,edit,hint);root.append(head,body);this.replaceChildren(root);}
 }
}
export type RadialShape=RadialGradientEditor.Types.RadialShape;export type RadialSize=RadialGradientEditor.Types.RadialSize;export type RadialGradientEditorOptions=RadialGradientEditor.Interfaces.RadialGradientEditorOptions;export default RadialGradientEditor.RadialGradientEditor;
