/** @module components/graphics/colors/ShapeGradientEditor */
import { Component, Css, Templates } from '../../../core/index.ts';
import type { RGBA } from './GradientEditor.ts';
const html=Templates.Template.Html;
export namespace ShapeGradientEditor {
 export interface ShapeStop{x:number;y:number;color:RGBA;radius?:number;}
 export interface ShapeGradientEditorOptions{points?:ShapeStop[];width?:number;height?:number;theme?:'dark'|'light';}
 interface State{points:ShapeStop[];selected:number;}const States=new WeakMap<HTMLElement,State>();const defaults=():ShapeStop[]=>[{x:.18,y:.22,color:{r:228,g:12,b:136,a:1},radius:.38},{x:.82,y:.18,color:{r:105,g:84,b:216,a:1},radius:.42},{x:.68,y:.82,color:{r:255,g:159,b:62,a:1},radius:.45}];const S=(e:HTMLElement):State=>{let s=States.get(e);if(!s){s={points:defaults(),selected:0};States.set(e,s);}return s;};const clamp=(v:number)=>Math.max(0,Math.min(1,Number.isFinite(v)?v:0));const rgba=(c:RGBA)=>`rgba(${Math.round(c.r)},${Math.round(c.g)},${Math.round(c.b)},${Math.max(0,Math.min(1,c.a))})`;const hex=(c:RGBA)=>`#${[c.r,c.g,c.b].map(v=>Math.round(Math.max(0,Math.min(255,v))).toString(16).padStart(2,'0')).join('')}`;
 export const Styles=new Css.Stylesheet([
  new Css.Rule('arianna-shape-gradient-editor,.ShapeGradientEditor',{Background:'var(--arianna-bg,#171a1d)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'12px',BoxSizing:'border-box',Color:'var(--arianna-text,#eef1f4)',Display:'block',FontFamily:'-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',Overflow:'hidden',Width:'470px',MaxWidth:'100%'}),
  new Css.Rule('.gs-head',{AlignItems:'center',Background:'var(--arianna-bg-2,#202428)',BorderBottom:'1px solid var(--arianna-border,#3a4046)',Display:'flex',Gap:'10px',Padding:'11px 13px'}),new Css.Rule('.gs-head strong',{Flex:'1',FontSize:'13px'}),new Css.Rule('.gs-badge',{Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'999px',Color:'var(--arianna-muted,#9aa2aa)',Font:'800 9px ui-monospace,monospace',Padding:'3px 8px',TextTransform:'uppercase'}),new Css.Rule('.gs-body',{Display:'grid',Gap:'11px',Padding:'12px'}),
  new Css.Rule('.gs-shape-canvas',{Background:'var(--arianna-bg-2,#202428)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'10px',Cursor:'copy',Height:'230px',Overflow:'hidden',Position:'relative',TouchAction:'none'}),new Css.Rule('.gs-point',{Appearance:'none',Background:'var(--point)',Border:'2px solid #fff',BorderRadius:'50%',BoxShadow:'0 0 0 1px #000',Cursor:'move',Height:'15px',Left:'calc(var(--x)*1%)',Padding:'0',Position:'absolute',Top:'calc(var(--y)*1%)',Transform:'translate(-50%,-50%)',Width:'15px'}),new Css.Rule('.gs-point[data-selected="true"]',{BoxShadow:'0 0 0 1px #000,0 0 0 4px var(--arianna-primary,#e40c88)'}),
  new Css.Rule('.gs-control-row',{AlignItems:'center',Display:'grid',Gap:'12px',GridTemplateColumns:'112px 1fr'}),new Css.Rule('.gs-radius-control',{Background:'radial-gradient(circle at center,var(--arianna-bg,#171a1d) 0 54%,var(--arianna-bg-2,#202428) 55% 100%)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'50%',Cursor:'crosshair',Height:'106px',Position:'relative',TouchAction:'none',Width:'106px'}),new Css.Rule('.gs-radius-ring',{Border:'2px solid var(--arianna-primary,#e40c88)',BorderRadius:'50%',Height:'calc(var(--radius)*84px)',Left:'50%',Position:'absolute',Top:'50%',Transform:'translate(-50%,-50%)',Width:'calc(var(--radius)*84px)'}),new Css.Rule('.gs-direction-grid',{Display:'grid',Gap:'5px',GridTemplateColumns:'repeat(3,34px)'}),new Css.Rule('.gs-dir,.gs-button',{Appearance:'none',Background:'var(--arianna-bg-2,#202428)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'7px',Color:'var(--arianna-text,#eef1f4)',Cursor:'pointer',Font:'700 11px system-ui',MinHeight:'31px'}),new Css.Rule('.gs-dir:hover,.gs-button:hover',{BorderColor:'var(--arianna-primary,#e40c88)'}),new Css.Rule('.gs-right',{Display:'grid',Gap:'8px'}),new Css.Rule('.gs-input',{Background:'var(--arianna-bg,#171a1d)',Border:'1px solid var(--arianna-border,#3a4046)',BorderRadius:'7px',BoxSizing:'border-box',Color:'var(--arianna-text,#eef1f4)',Font:'10px system-ui',MinWidth:'0',Padding:'7px'}),new Css.Rule('.gs-point-edit',{AlignItems:'center',Display:'grid',Gap:'7px',GridTemplateColumns:'42px 1fr 82px 82px auto'}),new Css.Rule('.gs-hint',{Color:'var(--arianna-muted,#9aa2aa)',FontSize:'9px'}),new Css.Rule('.ShapeGradientEditor[theme="light"]',{Background:'#f5f6f7',BorderColor:'#bcc2c7',Color:'#25292d'}),new Css.Rule('.ShapeGradientEditor[theme="light"] .gs-head,.ShapeGradientEditor[theme="light"] .gs-dir,.ShapeGradientEditor[theme="light"] .gs-button',{Background:'#fff'}),new Css.Rule('.ShapeGradientEditor[theme="light"] .gs-input',{Background:'#fff',Color:'#25292d'})
 ]);
 @Component('arianna-shape-gradient-editor',Styles,{Shadow:false,Attributes:['theme'],Properties:['points']})
 export class ShapeGradientEditor extends HTMLElement{
  public static readonly Styles=Styles;public template=html``;public onCreated():void{if(this.isConnected)this.onConnected();}public onConnected():void{this.classList.add('ShapeGradientEditor');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');this.Render();}
  public get points():ShapeStop[]{return structuredClone(S(this).points);}public set points(v:ShapeStop[]){S(this).points=Array.isArray(v)&&v.length?structuredClone(v):defaults();S(this).selected=0;this.Render();}public addPoint(x:number,y:number,c:RGBA):ShapeStop{const p={x:clamp(x),y:clamp(y),color:{...c},radius:.38};S(this).points.push(p);S(this).selected=S(this).points.length-1;this.Render();this.Fire();return p;}public removePoint(i:number):this{const s=S(this);if(s.points.length>1){s.points.splice(i,1);s.selected=Math.max(0,Math.min(s.selected,s.points.length-1));this.Render();this.Fire();}return this;}public updatePoint(i:number,patch:Partial<ShapeStop>):this{const p=S(this).points[i];if(p){Object.assign(p,patch);p.x=clamp(p.x);p.y=clamp(p.y);if(p.radius!=null)p.radius=Math.max(.05,Math.min(1,p.radius));if(patch.color)p.color={...patch.color};this.Render();this.Fire();}return this;}public setPoints(v:ShapeStop[]):this{this.points=v;this.Fire();return this;}public getPoints():ShapeStop[]{return this.points;}
  public toCanvasDataURL(type='image/png'):string{const canvas=document.createElement('canvas');canvas.width=512;canvas.height=320;const ctx=canvas.getContext('2d');if(!ctx)return'';ctx.fillStyle=this.getAttribute('theme')==='light'?'#ffffff':'#171b1f';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.globalCompositeOperation='screen';for(const p of S(this).points){const radius=(p.radius??.38)*Math.max(canvas.width,canvas.height);const g=ctx.createRadialGradient(p.x*canvas.width,p.y*canvas.height,0,p.x*canvas.width,p.y*canvas.height,radius);g.addColorStop(0,rgba(p.color));g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);}ctx.globalCompositeOperation='source-over';return canvas.toDataURL(type);}
  private Fire():void{this.dispatchEvent(new CustomEvent('arianna:change',{bubbles:true,composed:true,detail:{type:'shape',points:this.getPoints(),source:this}}));}
  private Render():void{const s=S(this),p=s.points[s.selected]??s.points[0],root=document.createElement('section'),head=document.createElement('header');head.className='gs-head';head.innerHTML='<strong>Gradient Studio</strong><span class="gs-badge">Shape</span>';const body=document.createElement('div');body.className='gs-body';const canvas=document.createElement('div');canvas.className='gs-shape-canvas';canvas.style.background=s.points.map(q=>`radial-gradient(circle at ${q.x*100}% ${q.y*100}%,${rgba(q.color)} 0%,rgba(0,0,0,0) ${(q.radius??.38)*100}%)`).join(',');s.points.forEach((q,i)=>{const b=document.createElement('button');b.className='gs-point';b.style.setProperty('--x',String(q.x*100));b.style.setProperty('--y',String(q.y*100));b.style.setProperty('--point',rgba(q.color));b.dataset.selected=String(i===s.selected);b.onclick=e=>{e.stopPropagation();s.selected=i;this.Render()};b.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const m=(ev:PointerEvent)=>{const r=canvas.getBoundingClientRect();q.x=clamp((ev.clientX-r.left)/r.width);q.y=clamp((ev.clientY-r.top)/r.height);this.Render();this.Fire()},u=()=>{window.removeEventListener('pointermove',m,true);window.removeEventListener('pointerup',u,true)};window.addEventListener('pointermove',m,true);window.addEventListener('pointerup',u,true)};canvas.appendChild(b)});canvas.onclick=e=>{if((e.target as Element).closest('.gs-point'))return;const r=canvas.getBoundingClientRect(),sample=s.points[s.selected]?.color??{r:228,g:12,b:136,a:1};this.addPoint((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height,{...sample})};
   const control=document.createElement('div');control.className='gs-control-row';const radius=document.createElement('div');radius.className='gs-radius-control';radius.style.setProperty('--radius',String(p.radius??.38));const ring=document.createElement('span');ring.className='gs-radius-ring';radius.appendChild(ring);const setRadius=(e:PointerEvent)=>{const r=radius.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2);p.radius=Math.max(.05,Math.min(1,Math.hypot(dx,dy)/(r.width*.42)));this.Render();this.Fire()};radius.onpointerdown=e=>{e.preventDefault();setRadius(e);const m=(x:PointerEvent)=>setRadius(x),u=()=>{window.removeEventListener('pointermove',m,true);window.removeEventListener('pointerup',u,true)};window.addEventListener('pointermove',m,true);window.addEventListener('pointerup',u,true)};const right=document.createElement('div');right.className='gs-right';const dirs=document.createElement('div');dirs.className='gs-direction-grid';const preset:[string,number,number][]=[['↖',.15,.15],['↑',.5,.15],['↗',.85,.15],['←',.15,.5],['•',.5,.5],['→',.85,.5],['↙',.15,.85],['↓',.5,.85],['↘',.85,.85]];for(const[l,x,y]of preset){const b=document.createElement('button');b.className='gs-dir';b.textContent=l;b.onclick=()=>{p.x=x;p.y=y;this.Render();this.Fire()};dirs.appendChild(b)}const hint2=document.createElement('div');hint2.className='gs-hint';hint2.textContent='Direction buttons reposition the selected shape stop. The circle controls its falloff radius.';right.append(dirs,hint2);control.append(radius,right);
   const edit=document.createElement('div');edit.className='gs-point-edit';const lab=document.createElement('span');lab.className='gs-hint';lab.textContent='Point';const col=document.createElement('input');col.type='color';col.value=hex(p.color);col.oninput=()=>{const x=col.value.slice(1);p.color={...p.color,r:parseInt(x.slice(0,2),16),g:parseInt(x.slice(2,4),16),b:parseInt(x.slice(4,6),16)};this.Render();this.Fire()};const xinp=document.createElement('input');xinp.className='gs-input';xinp.type='number';xinp.min='0';xinp.max='100';xinp.value=String(Math.round(p.x*100));xinp.onchange=()=>{p.x=clamp(Number(xinp.value)/100);this.Render();this.Fire()};const yin=document.createElement('input');yin.className='gs-input';yin.type='number';yin.min='0';yin.max='100';yin.value=String(Math.round(p.y*100));yin.onchange=()=>{p.y=clamp(Number(yin.value)/100);this.Render();this.Fire()};const del=document.createElement('button');del.className='gs-button';del.textContent='Delete';del.disabled=s.points.length<=1;del.onclick=()=>this.removePoint(s.selected);edit.append(lab,col,xinp,yin,del);const hint=document.createElement('div');hint.className='gs-hint';hint.textContent='Click anywhere in the preview to add a shape stop · drag points to move them · drag the radius circle to change falloff.';body.append(canvas,control,edit,hint);root.append(head,body);this.replaceChildren(root);}
 }
}
export type ShapeStop=ShapeGradientEditor.ShapeStop;export type ShapeGradientEditorOptions=ShapeGradientEditor.ShapeGradientEditorOptions;export default ShapeGradientEditor.ShapeGradientEditor;
