/**
 * @module components/display/Snackbar
 * @version 2.0.0
 * @description AriannA 2 component normalized to the Accordion light-DOM convention.
 */
import { Component, Css } from '../../core/index.ts';


export namespace Snackbar{export namespace Types{export type Theme='dark'|'light';export type Variant='default'|'info'|'success'|'warning'|'danger';export type Position='top-left'|'top-center'|'top-right'|'bottom-left'|'bottom-center'|'bottom-right';}export namespace Interfaces{export interface Options{message?:string;variant?:Types.Variant;duration?:number;position?:Types.Position;action?:string;theme?:Types.Theme;}}}
const Timers=new WeakMap<HTMLElement,number>();
function Container(position:Snackbar.Types.Position){const id=`Arianna-Snackbar-${position}`;let el=document.getElementById(id) as HTMLDivElement|null;if(!el){el=document.createElement('div');el.id=id;Object.assign(el.style,{display:'flex',flexDirection:'column',gap:'8px',pointerEvents:'none',position:'fixed',zIndex:'5000',padding:'12px',maxWidth:'400px'});if(position.startsWith('top'))el.style.top='0';else el.style.bottom='0';if(position.endsWith('left'))el.style.left='0';else if(position.endsWith('right'))el.style.right='0';else{el.style.left='50%';el.style.transform='translateX(-50%)'}document.body.append(el)}return el}
export const Styles=new Css.Stylesheet([

        new Css.Rule('.Snackbar', {
            '--arianna-bg':'#17181c','--arianna-bg-2':'#1d1e23','--arianna-bg-3':'#24262b',
            '--arianna-text':'#e6e8eb','--arianna-muted':'#9aa0aa','--arianna-dim':'#6f7580',
            '--arianna-border':'#303238','--arianna-primary':'#e40c88','--arianna-info':'#60a5fa',
            '--arianna-success':'#26a69a','--arianna-warning':'#f5a623','--arianna-danger':'#ef5350'
        }),
        new Css.Rule('.Snackbar[theme="light"]', {
            '--arianna-bg':'#ffffff','--arianna-bg-2':'#fbfbfc','--arianna-bg-3':'#f3f3f5',
            '--arianna-text':'#1c1e21','--arianna-muted':'#626873','--arianna-dim':'#8a8f98',
            '--arianna-border':'#e2e2e6','--arianna-primary':'#e40c88','--arianna-info':'#2f6feb',
            '--arianna-success':'#168a78','--arianna-warning':'#b66c00','--arianna-danger':'#c93645'
        }),
 new Css.Rule('.Snackbar',{AlignItems:'center',Background:'var(--arianna-bg-2)',Border:'1px solid var(--arianna-border)',BorderRadius:'8px',BoxShadow:'0 8px 28px rgba(0,0,0,.28)',Color:'var(--arianna-text)',Display:'flex',Gap:'10px',MinWidth:'220px',Opacity:'0',Padding:'10px 14px',PointerEvents:'all',Transform:'translateY(6px)',Transition:'opacity .22s,transform .22s'}),new Css.Rule('.Snackbar-On',{Opacity:'1',Transform:'none'}),new Css.Rule('.Snackbar[variant="success"]',{Background:'var(--arianna-success)',Color:'#fff'}),new Css.Rule('.Snackbar[variant="warning"]',{Background:'var(--arianna-warning)',Color:'#111'}),new Css.Rule('.Snackbar[variant="danger"]',{Background:'var(--arianna-danger)',Color:'#fff'}),new Css.Rule('.Snackbar[variant="info"]',{Background:'var(--arianna-info)',Color:'#fff'}),new Css.Rule('.Snackbar-Message',{Flex:'1',FontSize:'.82rem'}),new Css.Rule('.Snackbar-Action,.Snackbar-Close',{Appearance:'none',Background:'transparent',Border:'0',Color:'inherit',Cursor:'pointer',Font:'inherit',Padding:'0'})
]);
@Component('arianna-snackbar',Styles,{Shadow:false,Attributes:['message','variant','duration','position','action','theme']})
export class Snackbar extends HTMLElement{public static readonly Styles=Styles;static DefaultSheet(){return Styles}constructor(o:Snackbar.Interfaces.Options={}){super();if(o.message)this.message=o.message;if(o.variant)this.variant=o.variant;if(o.duration!=null)this.duration=o.duration;if(o.position)this.position=o.position;if(o.action)this.action=o.action;if(o.theme)this.theme=o.theme}onConnected(){this.classList.add('Snackbar');if(!this.hasAttribute('theme'))this.setAttribute('theme','dark');this.Render();if(!this.classList.contains('Snackbar-On'))this.style.display='none'}onAttributeChanged(){if(this.isConnected)this.Render()}onUnmount(){const t=Timers.get(this);if(t)clearTimeout(t)}private Render(){const msg=document.createElement('span');msg.className='Snackbar-Message';msg.textContent=this.message;const nodes:Node[]=[msg];if(this.action){const a=document.createElement('button');a.className='Snackbar-Action';a.type='button';a.textContent=this.action;a.addEventListener('click',()=>{this.dispatchEvent(new CustomEvent('arianna:action',{bubbles:true,detail:{}}));this.hide()});nodes.push(a)}const close=document.createElement('button');close.className='Snackbar-Close';close.type='button';close.textContent='✕';close.addEventListener('click',()=>this.hide());nodes.push(close);this.replaceChildren(...nodes)}show(){const c=Container(this.position);if(this.parentElement!==c)c.append(this);this.style.display='';this.classList.add('Snackbar-On');const old=Timers.get(this);if(old)clearTimeout(old);if(this.duration>0)Timers.set(this,window.setTimeout(()=>this.hide(),this.duration));this.dispatchEvent(new CustomEvent('arianna:show',{bubbles:true,detail:{}}));return this}hide(){const old=Timers.get(this);if(old)clearTimeout(old);this.classList.remove('Snackbar-On');this.style.display='none';this.dispatchEvent(new CustomEvent('arianna:hide',{bubbles:true,detail:{}}));return this}static show(message:string,o:Snackbar.Interfaces.Options={}){const s=new Snackbar(o);s.message=message;s.show();return s}get message(){return this.getAttribute('message')??''}set message(v:string){v?this.setAttribute('message',v):this.removeAttribute('message')}get variant(){return(this.getAttribute('variant')??'default') as Snackbar.Types.Variant}set variant(v:Snackbar.Types.Variant){this.setAttribute('variant',v)}get duration(){return parseInt(this.getAttribute('duration')??'4000',10)||0}set duration(v:number){this.setAttribute('duration',String(v))}get position(){return(this.getAttribute('position')??'bottom-center') as Snackbar.Types.Position}set position(v:Snackbar.Types.Position){this.setAttribute('position',v)}get action(){return this.getAttribute('action')??''}set action(v:string){v?this.setAttribute('action',v):this.removeAttribute('action')}get theme(){return(this.getAttribute('theme')??'dark') as Snackbar.Types.Theme}set theme(v:Snackbar.Types.Theme){this.setAttribute('theme',v)}}
export default Snackbar;export type SnackbarOptions=Snackbar.Interfaces.Options;
