import {Modifier3D as BaseNamespace} from './Base.ts';
import {BendModifier3D as BendNamespace} from './standard/BendModifier3D.ts';
import {TwistModifier3D as TwistNamespace} from './standard/TwistModifier3D.ts';
import {TaperModifier3D as TaperNamespace} from './standard/TaperModifier3D.ts';
import {SqueezeModifier3D as SqueezeNamespace} from './standard/SqueezeModifier3D.ts';
import {PushModifier3D as PushNamespace} from './standard/PushModifier3D.ts';
import {NoiseModifier3D as NoiseNamespace} from './standard/NoiseModifier3D.ts';
import {MirrorModifier3D as MirrorNamespace} from './standard/MirrorModifier3D.ts';
import {RelaxModifier3D as RelaxNamespace} from './standard/RelaxModifier3D.ts';
import {SubdivisionModifier3D as SubdivisionNamespace} from './standard/SubdivisionModifier3D.ts';
import {MeshSmoothModifier3D as MeshSmoothNamespace} from './standard/MeshSmoothModifier3D.ts';
import {ExtrudeModifier3D as ExtrudeNamespace} from './standard/ExtrudeModifier3D.ts';
import {BevelModifier3D as BevelNamespace} from './standard/BevelModifier3D.ts';
import {BevelProfileModifier3D as BevelProfileNamespace} from './standard/BevelProfileModifier3D.ts';
import {SweepModifier3D as SweepNamespace} from './standard/SweepModifier3D.ts';
import {SurfaceModifier3D as SurfaceNamespace} from './standard/SurfaceModifier3D.ts';
import {ArrayModifier3D as ArrayNamespace} from './standard/ArrayModifier3D.ts';
import {WaveModifier3D as WaveNamespace} from './standard/WaveModifier3D.ts';
import {LatheModifier3D as LatheNamespace} from './standard/LatheModifier3D.ts';
import {Mover3D as Mover3DNamespace} from './basic/Mover3D.ts';
import {Resizer3D as Resizer3DNamespace} from './basic/Resizer3D.ts';
import {Rotator3D as Rotator3DNamespace} from './basic/Rotator3D.ts';
import {Rounder3D as Rounder3DNamespace} from './basic/Rounder3D.ts';
import {Skewer3D as Skewer3DNamespace} from './basic/Skewer3D.ts';
import {CrossSection3D as CrossNamespace} from './standard/CrossSection3D.ts';
export const Modifier3D = BaseNamespace.Modifier3D;
export const Modifier3DElement = BaseNamespace.Modifier3DElement;
export const _v3 = BaseNamespace._v3;
export const _vAdd = BaseNamespace._vAdd;
export const _vSub = BaseNamespace._vSub;
export const _vScale = BaseNamespace._vScale;
export const _vLen = BaseNamespace._vLen;
export const _vNorm = BaseNamespace._vNorm;
export const _vCross = BaseNamespace._vCross;
export const _vLerp = BaseNamespace._vLerp;
export const _cloneGeom = BaseNamespace._cloneGeom;
export const _recomputeNormals = BaseNamespace._recomputeNormals;

export type Vec3Like = BaseNamespace.Interfaces.Vec3Like;
export type Geometry3Like = BaseNamespace.Interfaces.Geometry3Like;
export type MeshLike = BaseNamespace.Interfaces.MeshLike;
export type SceneLike = BaseNamespace.Interfaces.SceneLike;
export type CameraLike = BaseNamespace.Interfaces.CameraLike;
export type Viewport3DLike = BaseNamespace.Interfaces.Viewport3DLike;
export type ModifierSelection3D = BaseNamespace.Interfaces.SelectionLike;

export const BendModifier3D=BendNamespace.BendModifier3D;
export const BendModifierElement=BendNamespace.BendModifierElement;
export const TwistModifier3D=TwistNamespace.TwistModifier3D;
export const TwistModifierElement=TwistNamespace.TwistModifierElement;
export const TaperModifier3D=TaperNamespace.TaperModifier3D;
export const TaperModifierElement=TaperNamespace.TaperModifierElement;
export const SqueezeModifier3D=SqueezeNamespace.SqueezeModifier3D;
export const SqueezeModifierElement=SqueezeNamespace.SqueezeModifierElement;
export const PushModifier3D=PushNamespace.PushModifier3D;
export const PushModifierElement=PushNamespace.PushModifierElement;
export const NoiseModifier3D=NoiseNamespace.NoiseModifier3D;
export const NoiseModifierElement=NoiseNamespace.NoiseModifierElement;
export const MirrorModifier3D=MirrorNamespace.MirrorModifier3D;
export const MirrorModifierElement=MirrorNamespace.MirrorModifierElement;
export const RelaxModifier3D=RelaxNamespace.RelaxModifier3D;
export const RelaxModifierElement=RelaxNamespace.RelaxModifierElement;
export const SubdivisionModifier3D=SubdivisionNamespace.SubdivisionModifier3D;
export const SubdivisionModifierElement=SubdivisionNamespace.SubdivisionModifierElement;
export const MeshSmoothModifier3D=MeshSmoothNamespace.MeshSmoothModifier3D;
export const MeshSmoothModifierElement=MeshSmoothNamespace.MeshSmoothModifierElement;
export const ExtrudeModifier3D=ExtrudeNamespace.ExtrudeModifier3D;
export const ExtrudeModifierElement=ExtrudeNamespace.ExtrudeModifierElement;
export const BevelModifier3D=BevelNamespace.BevelModifier3D;
export const BevelModifierElement=BevelNamespace.BevelModifierElement;
export const BevelProfileModifier3D=BevelProfileNamespace.BevelProfileModifier3D;
export const BevelProfileModifierElement=BevelProfileNamespace.BevelProfileModifierElement;
export const SweepModifier3D=SweepNamespace.SweepModifier3D;
export const SweepModifierElement=SweepNamespace.SweepModifierElement;
export const SurfaceModifier3D=SurfaceNamespace.SurfaceModifier3D;
export const SurfaceModifierElement=SurfaceNamespace.SurfaceModifierElement;
export const ArrayModifier3D=ArrayNamespace.ArrayModifier3D;
export const ArrayModifierElement=ArrayNamespace.ArrayModifierElement;
export const WaveModifier3D=WaveNamespace.WaveModifier3D;
export const WaveModifierElement=WaveNamespace.WaveModifierElement;
export const LatheModifier3D=LatheNamespace.LatheModifier3D;
export const LatheModifierElement=LatheNamespace.LatheModifierElement;
export const Mover3D=Mover3DNamespace.Mover3D;
export const Mover3DElement=Mover3DNamespace.Mover3DElement;
export type Mover3DOptions=Mover3DNamespace.Options;
export const Resizer3D=Resizer3DNamespace.Resizer3D;
export const Resizer3DElement=Resizer3DNamespace.Resizer3DElement;
export type Resizer3DOptions=Resizer3DNamespace.Options;
export const Rotator3D=Rotator3DNamespace.Rotator3D;
export const Rotator3DElement=Rotator3DNamespace.Rotator3DElement;
export type Rotator3DOptions=Rotator3DNamespace.Options;
export const Rounder3D=Rounder3DNamespace.Rounder3D;
export const Rounder3DElement=Rounder3DNamespace.Rounder3DElement;
export type Rounder3DOptions=Rounder3DNamespace.Options;
export const Skewer3D=Skewer3DNamespace.Skewer3D;
export const Skewer3DElement=Skewer3DNamespace.Skewer3DElement;
export type Skewer3DOptions=Skewer3DNamespace.Options;
export const CrossSection3D=CrossNamespace.CrossSection3D;
export const CrossSectionModifier3D=CrossNamespace.CrossSectionModifier3D;
export {createCrossSection3D,type CrossSectionCage3D} from './standard/CrossSection3D.ts';
export type {Options as StandardModifier3DOptions} from './standard/GeometryKernel3D.ts';
export type ArrayModifierOptions=ArrayNamespace.Interfaces.ArrayModifierOptions;
export type WaveModifierOptions=WaveNamespace.Interfaces.WaveModifierOptions;
export type LatheOptions=LatheNamespace.Interfaces.LatheOptions;
export type LatheProfilePoint=LatheNamespace.Interfaces.ProfilePoint;

export const Modifiers3DRegistry={BendModifier3D,TwistModifier3D,TaperModifier3D,SqueezeModifier3D,PushModifier3D,NoiseModifier3D,MirrorModifier3D,RelaxModifier3D,SubdivisionModifier3D,MeshSmoothModifier3D,ExtrudeModifier3D,BevelModifier3D,BevelProfileModifier3D,SweepModifier3D,SurfaceModifier3D,ArrayModifier3D,WaveModifier3D,LatheModifier3D,Mover3D,Resizer3D,Rotator3D,Rounder3D,Skewer3D,CrossSection3D};
