import type { AstNode } from './Parser.ts';
export interface IR { html:string; ops:string[]; }
const esc=(s:string)=>JSON.stringify(s);
function expression(x:string,aliases:string[]):string{let y=x.trim();for(const a of aliases){const safe=a.replace(/[$]/g,'\\$&');y=y.replace(new RegExp(`(?<![.$\\w])${safe}(?![\\w$])`,'g'),`scope.${a}`);}return `(function(){return (${y});}).call(ctx)`;}
function interpolation(text:string,aliases:string[]):string{const re=/\{\{\s*([\s\S]+?)\s*\}\}/g;let m:RegExpExecArray|null,last=0,parts:string[]=[];while((m=re.exec(text))){if(m.index>last)parts.push(esc(text.slice(last,m.index)));parts.push(`String(${expression(m[1],aliases)} ?? '')`);last=re.lastIndex;}if(last<text.length)parts.push(esc(text.slice(last)));return parts.length?parts.join('+'):esc(text);}
export function Transform(root:AstNode, aliases:string[]=[]):IR{
 let html='';const ops:string[]=[];const voids=new Set(['area','base','br','col','embed','hr','img','input','link','meta','param','source','track','wbr']);
 function emit(node:any,path:number[],local:string[]){if(node.type==='raw'){html+=node.html;return;}if(node.type==='text'){if(/\{\{/.test(node.text)){html+='<!--ar:t-->';ops.push(`{k:'text',p:${JSON.stringify(path)},e:(ctx,scope)=>${interpolation(node.text,local)}}`);}else html+=node.text;return;}if(node.type!=='el')return;const amap=new Map<string,string>(node.attrs);const forv=amap.get('a-for');const ifv=amap.get('a-if');if(forv||ifv){html+='<!--ar:s-->';const drop=forv?'a-for':'a-if';const clone={...node,attrs:node.attrs.filter(([n]:[string,string])=>n!==drop)};if(forv){const mm=forv.match(/^\s*([\w$]+)(?:\s*,\s*([\w$]+))?\s+(?:in|of)\s+([\s\S]+)$/);if(!mm)throw new Error(`Bad a-for: ${forv}`);const item=mm[1],index=mm[2];const child=Transform({type:'root',children:[clone]} as any,[...local,item,...(index?[index]:[])]);const key=amap.get('a-key')||amap.get(':key');ops.push(`{k:'for',p:${JSON.stringify(path)},item:${esc(item)},${index?`index:${esc(index)},`:''}e:(ctx,scope)=>${expression(mm[3],local)},${key?`key:(ctx,scope)=>${expression(key,[...local,item,...(index?[index]:[])])},`:''}c:{html:${esc(child.html)},ops:[${child.ops.join(',')}]}}`);}else{const child=Transform({type:'root',children:[clone]} as any,local);ops.push(`{k:'if',p:${JSON.stringify(path)},e:(ctx,scope)=>${expression(ifv!,local)},c:{html:${esc(child.html)},ops:[${child.ops.join(',')}]}}`);}return;}html+=`<${node.tag}`;for(const [n,v] of node.attrs){if(n.startsWith(':')||n.startsWith('@')||n==='a-html'||n==='a-key')continue;html+=v===''?` ${n}`:` ${n}=${esc(v)}`;}html+='>';for(const [n,v] of node.attrs){if(n.startsWith(':'))ops.push(`{k:'attr',p:${JSON.stringify(path)},n:${esc(n.slice(1))},e:(ctx,scope)=>${expression(v,local)}}`);else if(n.startsWith('@'))ops.push(`{k:'event',p:${JSON.stringify(path)},n:${esc(n.slice(1))},e:(ctx,scope)=>${expression(v,local)}}`);else if(n==='a-html')ops.push(`{k:'html',p:${JSON.stringify(path)},e:(ctx,scope)=>${expression(v,local)}}`);}let ci=0;for(const child of node.children)emit(child,[...path,ci++],local);if(!voids.has(node.tag.toLowerCase()))html+=`</${node.tag}>`;}
 let i=0;for(const child of (root as any).children)emit(child,[i++],aliases);return{html,ops};
}
